const TOKEN_KEY='nhPortalToken',ROLE_KEY='nhPortalRole';const $=id=>document.getElementById(id);const token=localStorage.getItem(TOKEN_KEY);if(!token||localStorage.getItem(ROLE_KEY)!=='ADMIN')location.replace('/colaborador/');let quotes=[],inspections=[];
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});const date=v=>v?new Date(v).toLocaleString('pt-BR'):'—';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(path,options={}){const h=new Headers(options.headers||{});h.set('Authorization',`Bearer ${token}`);const r=await fetch(path,{...options,headers:h});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.message||'Erro ao carregar dados.')}return r.json()}
function msg(t,type='error'){const e=$('message');e.className=`message ${type}`;e.textContent=t}
function statusBadge(text,kind=''){return `<span class="badge ${kind}">${esc(text)}</span>`}
async function load(){try{const [consultantsData,quotesData,inspectionData,prices,optionals,audit]=await Promise.all([api('/api/admin/consultants'),api('/api/admin/quotes'),api('/api/admin/inspections'),api('/api/admin/catalog/prices'),api('/api/admin/catalog/optionals'),api('/api/admin/catalog/audit')]);quotes=quotesData;inspections=inspectionData;renderConsultants(consultantsData);renderQuotes();renderInspections();renderPrices(prices);renderOptionals(optionals);renderAudit(audit);$('kpi-consultants').textContent=consultantsData.filter(c=>c.active).length;$('kpi-quotes').textContent=quotes.length;$('kpi-inspections').textContent=inspections.length;$('kpi-accepted').textContent=quotes.filter(q=>q.status==='ACCEPTED').length}catch(e){msg(e.message)}}
function renderConsultants(data){$('consultants-body').innerHTML=data.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.source)}</td><td>${c.quoteCount}</td><td>${c.inspectionCount}</td><td>${statusBadge(c.active?'Ativo':'Inativo',c.active?'ok':'off')}</td><td><button class="${c.active?'danger':'outline'}" data-consultant="${c.id}" data-active="${!c.active}">${c.active?'Desativar':'Ativar'}</button></td></tr>`).join('');document.querySelectorAll('[data-consultant]').forEach(b=>b.onclick=async()=>{try{await api(`/api/admin/consultants/${b.dataset.consultant}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:b.dataset.active==='true'})});msg('Consultor atualizado.','success');load()}catch(e){msg(e.message)}})}
function quoteLabel(q){if(q.expired)return statusBadge('Expirada','off');if(q.status==='ACCEPTED')return statusBadge('Aceita','ok');if(q.status==='DECLINED')return statusBadge('Recusada','off');return statusBadge('Pendente','warn')}
function renderQuotes(){const f=$('quote-filter').value.toLowerCase();$('quotes-body').innerHTML=quotes.filter(q=>`${q.consultantName} ${q.customerName} ${q.plate}`.toLowerCase().includes(f)).map(q=>`<tr><td>${esc(q.quoteNumber)}</td><td>${esc(q.consultantName)}</td><td>${esc(q.customerName)}</td><td>${esc(q.plate)}</td><td>${q.zeroKm?'Sim':'Não'}</td><td>${esc(q.selectedPlanName)}</td><td>${brl.format(q.monthlyValue)}</td><td>${date(q.validUntil)}</td><td>${quoteLabel(q)}</td><td><a class="button outline" href="/api/quotes/${q.id}/pdf" target="_blank">PDF</a></td></tr>`).join('')}
function renderInspections(){const f=$('inspection-filter').value.toLowerCase();$('inspections-body').innerHTML=inspections.filter(i=>`${i.consultantName} ${i.associateName} ${i.plate}`.toLowerCase().includes(f)).map(i=>`<tr><td>${esc(i.associateName)}</td><td>${esc(i.consultantName)}</td><td>${esc(i.plate)}</td><td>${i.requestType==='NEW_INSPECTION'?'Nova vistoria':'Atualização de boleto'}</td><td>${statusBadge(i.status==='COMPLETED'?'Concluída':'Pendente',i.status==='COMPLETED'?'ok':'warn')}</td><td>${date(i.createdAt)}</td><td><div class="actions" style="margin:0">${i.driveFolderUrl?`<a class="button outline" href="${esc(i.driveFolderUrl)}" target="_blank">Drive</a>`:`<a class="button outline" href="${esc(i.publicUrl)}" target="_blank">Link</a>`}${i.teamWhatsappUrl?`<a class="button secondary" href="${esc(i.teamWhatsappUrl)}" target="_blank">WhatsApp equipe</a>`:''}</div></td></tr>`).join('')}
function moneyEditor(id,value,type){return `<div class="inline-edit"><input data-value="${type}-${id}" value="${Number(value).toFixed(2).replace('.',',')}" inputmode="decimal"><button class="secondary" data-save="${type}-${id}">Salvar</button></div>`}
function renderPrices(data){$('prices-body').innerHTML=data.map(p=>`<tr><td>${esc(p.planName)}</td><td>${esc(p.category)}</td><td>${esc(p.region)}</td><td>${brl.format(p.minValue)} a ${brl.format(p.maxValue)}</td><td>${moneyEditor(p.id,p.monthlyPrice,'price')}</td></tr>`).join('');bindSaves()}
function renderOptionals(data){$('optionals-body').innerHTML=data.map(p=>`<tr><td>${esc(p.planName)}</td><td>${esc(p.coverageName)}</td><td>${esc(p.detail||'—')}</td><td>${moneyEditor(p.id,p.monthlyPrice||0,'optional')}</td></tr>`).join('');bindSaves()}
function bindSaves(){document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const [type,id]=b.dataset.save.split('-');const input=document.querySelector(`[data-value="${b.dataset.save}"]`);const value=Number(input.value.replace(/\./g,'').replace(',','.'));if(Number.isNaN(value))return msg('Informe um valor válido.');try{await api(`/api/admin/catalog/${type==='price'?'prices':'optionals'}/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({monthlyPrice:value})});msg('Valor atualizado com sucesso.','success');load()}catch(e){msg(e.message)}})}
function renderAudit(data){$('audit-body').innerHTML=data.map(a=>`<tr><td>${date(a.changedAt)}</td><td>${esc(a.description)}</td><td>${brl.format(a.oldValue||0)}</td><td>${brl.format(a.newValue||0)}</td><td>${esc(a.changedBy)}</td></tr>`).join('')}
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[id^="tab-"]').forEach(s=>s.hidden=s.id!==`tab-${b.dataset.tab}`)});$('quote-filter').oninput=renderQuotes;$('inspection-filter').oninput=renderInspections;$('logout').onclick=()=>{localStorage.clear();location.href='/colaborador/'};load();
