-- Ajusta o catálogo de coberturas conforme as regras comerciais informadas em 03/08/2026.
-- Os opcionais permanecem fora da tabela de comparação e só aparecem quando contratados.

INSERT INTO coverages (code, name)
VALUES ('THIRD_PARTY_BASE', 'Danos ao veículo de terceiros')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

UPDATE coverages SET name = 'Adicional para danos a terceiros' WHERE code = 'THIRD_PARTY';
UPDATE coverages SET name = 'Colisão, capotamento ou queda' WHERE code = 'COLLISION';
UPDATE coverages SET name = 'Rastreamento obrigatório' WHERE code = 'TRACKER';

-- Categorias registradas para futura ativação. Não são exibidas sem tabela de valores e critérios comerciais.
INSERT INTO vehicle_categories (code, name) VALUES
('SCOOTER_ELECTRIC', 'Scooters e motos elétricas'),
('MOTORCYCLE_PROMO_2026', 'Motocicletas — tabela promocional 2026')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO plans (code, name, subtitle, category_id, region, display_order, active, extra_above, extra_step, extra_increment, extra_base_price)
VALUES
('MOTO_SCOOTER_ELECTRIC', 'Plano Premium', 'Scooters e motos elétricas', (SELECT id FROM vehicle_categories WHERE code='SCOOTER_ELECTRIC'), 'NATIONAL', 1, FALSE, NULL, NULL, NULL, NULL),
('MOTO_PROMO_2026', 'Tabela Promocional 2026', 'Honda, Yamaha, Shineray e Avelloz até 300 cc', (SELECT id FROM vehicle_categories WHERE code='MOTORCYCLE_PROMO_2026'), 'NATIONAL', 1, FALSE, NULL, NULL, NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    subtitle = EXCLUDED.subtitle,
    category_id = EXCLUDED.category_id,
    region = EXCLUDED.region,
    display_order = EXCLUDED.display_order,
    active = FALSE;

UPDATE plans SET subtitle = 'Honda, Yamaha, Shineray e Avelloz até 300 cc' WHERE code IN ('MOTO_COMPLETO_NE', 'MOTO_COMPLETO_CAPITAL');
UPDATE plans SET subtitle = 'Montadoras diversas até 300 cc' WHERE code IN ('MOTO_RF_NE', 'MOTO_RF_CAPITAL');
UPDATE plans SET subtitle = 'Montadoras diversas acima de 300 cc' WHERE code IN ('MOTO_RF_OVER_NE', 'MOTO_RF_OVER_CAPITAL');

DELETE FROM plan_coverages
WHERE plan_id IN (
    SELECT id FROM plans WHERE code IN (
        'CAR_COMPLETO',
        'CAR_ECONOMICO',
        'CAR_IMPORTED',
        'MOTO_COMPLETO_CAPITAL',
        'MOTO_COMPLETO_NE',
        'MOTO_PROMO_2026',
        'MOTO_RF_CAPITAL',
        'MOTO_RF_NE',
        'MOTO_RF_OVER_CAPITAL',
        'MOTO_RF_OVER_NE',
        'MOTO_SCOOTER_ELECTRIC',
        'TRUCK_DIAMANTE_PLUS',
        'TRUCK_OURO_PLUS',
        'TRUCK_OURO_SDT',
        'UTILITY_COMPLETO',
        'UTILITY_ECONOMICO'
    )
);

INSERT INTO plan_coverages (plan_id, coverage_id, status, detail, monthly_price, sort_order)
SELECT p.id, c.id, data.status, data.detail, data.monthly_price, data.sort_order
FROM (VALUES
    ('MOTO_COMPLETO_NE', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('MOTO_COMPLETO_CAPITAL', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('MOTO_COMPLETO_NE', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('MOTO_COMPLETO_CAPITAL', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('MOTO_COMPLETO_NE', 'COLLISION', 'INCLUDED', 'Colisão ou queda', NULL, 3),
    ('MOTO_COMPLETO_CAPITAL', 'COLLISION', 'INCLUDED', 'Colisão ou queda', NULL, 3),
    ('MOTO_COMPLETO_NE', 'FIRE', 'INCLUDED', 'Incêndio', NULL, 4),
    ('MOTO_COMPLETO_CAPITAL', 'FIRE', 'INCLUDED', 'Incêndio', NULL, 4),
    ('MOTO_COMPLETO_NE', 'TOTAL_LOSS', 'INCLUDED', NULL, NULL, 5),
    ('MOTO_COMPLETO_CAPITAL', 'TOTAL_LOSS', 'INCLUDED', NULL, NULL, 5),
    ('MOTO_COMPLETO_NE', 'MOTO_REPLACEMENT', 'OPTIONAL', '30 diárias de moto reserva em caso de colisão, no valor de R$ 20,00 por dia', 10.00, 6),
    ('MOTO_COMPLETO_CAPITAL', 'MOTO_REPLACEMENT', 'OPTIONAL', '30 diárias de moto reserva em caso de colisão, no valor de R$ 20,00 por dia', 10.00, 6),
    ('MOTO_COMPLETO_NE', 'TOW_BREAKDOWN', 'OPTIONAL', 'Até 300 km por pane mecânica ou elétrica (150 km de ida e 150 km de volta); 1 acionamento mensal e 6 anuais', 15.00, 7),
    ('MOTO_COMPLETO_CAPITAL', 'TOW_BREAKDOWN', 'OPTIONAL', 'Até 300 km por pane mecânica ou elétrica (150 km de ida e 150 km de volta); 1 acionamento mensal e 6 anuais', 15.00, 7),
    ('MOTO_COMPLETO_NE', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão (500 km de ida e 500 km de volta)', NULL, 8),
    ('MOTO_COMPLETO_CAPITAL', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão (500 km de ida e 500 km de volta)', NULL, 8),
    ('MOTO_COMPLETO_NE', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 10 mil', NULL, 9),
    ('MOTO_COMPLETO_CAPITAL', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 10 mil', NULL, 9),
    ('MOTO_COMPLETO_NE', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 10 mil para danos ao veículo de terceiros', 10.00, 10),
    ('MOTO_COMPLETO_CAPITAL', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 10 mil para danos ao veículo de terceiros', 10.00, 10),
    ('MOTO_COMPLETO_NE', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 11),
    ('MOTO_COMPLETO_CAPITAL', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 11),
    ('MOTO_COMPLETO_NE', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 600,00; em roubo ou furto não há taxa de participação', NULL, 12),
    ('MOTO_COMPLETO_CAPITAL', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 600,00; em roubo ou furto não há taxa de participação', NULL, 12),
    ('MOTO_COMPLETO_NE', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 13),
    ('MOTO_COMPLETO_CAPITAL', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 13),
    ('MOTO_COMPLETO_NE', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 14),
    ('MOTO_COMPLETO_CAPITAL', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 14),
    ('MOTO_COMPLETO_NE', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 15),
    ('MOTO_COMPLETO_CAPITAL', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 15),
    ('MOTO_COMPLETO_NE', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 16),
    ('MOTO_COMPLETO_CAPITAL', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 16),
    ('MOTO_COMPLETO_NE', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 17),
    ('MOTO_COMPLETO_CAPITAL', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 17),
    ('MOTO_RF_NE', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('MOTO_RF_CAPITAL', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('MOTO_RF_NE', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('MOTO_RF_CAPITAL', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('MOTO_RF_NE', 'MOTO_REPLACEMENT', 'OPTIONAL', '30 diárias de moto reserva em caso de colisão, no valor de R$ 20,00 por dia', 10.00, 3),
    ('MOTO_RF_CAPITAL', 'MOTO_REPLACEMENT', 'OPTIONAL', '30 diárias de moto reserva em caso de colisão, no valor de R$ 20,00 por dia', 10.00, 3),
    ('MOTO_RF_NE', 'TOW_BREAKDOWN', 'OPTIONAL', 'Até 300 km por pane mecânica ou elétrica; 1 acionamento mensal e 6 anuais', 15.00, 4),
    ('MOTO_RF_CAPITAL', 'TOW_BREAKDOWN', 'OPTIONAL', 'Até 300 km por pane mecânica ou elétrica; 1 acionamento mensal e 6 anuais', 15.00, 4),
    ('MOTO_RF_NE', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão', NULL, 5),
    ('MOTO_RF_CAPITAL', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão', NULL, 5),
    ('MOTO_RF_NE', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 10 mil', NULL, 6),
    ('MOTO_RF_CAPITAL', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 10 mil', NULL, 6),
    ('MOTO_RF_NE', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 10 mil para danos ao veículo de terceiros', 10.00, 7),
    ('MOTO_RF_CAPITAL', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 10 mil para danos ao veículo de terceiros', 10.00, 7),
    ('MOTO_RF_NE', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 8),
    ('MOTO_RF_CAPITAL', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 8),
    ('MOTO_RF_NE', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 600,00; em roubo ou furto não há taxa de participação', NULL, 9),
    ('MOTO_RF_CAPITAL', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 600,00; em roubo ou furto não há taxa de participação', NULL, 9),
    ('MOTO_RF_NE', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 10),
    ('MOTO_RF_CAPITAL', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 10),
    ('MOTO_RF_NE', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 11),
    ('MOTO_RF_CAPITAL', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 11),
    ('MOTO_RF_NE', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 12),
    ('MOTO_RF_CAPITAL', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 12),
    ('MOTO_RF_NE', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 13),
    ('MOTO_RF_CAPITAL', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 13),
    ('MOTO_RF_NE', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 14),
    ('MOTO_RF_CAPITAL', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 14),
    ('MOTO_RF_OVER_NE', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('MOTO_RF_OVER_CAPITAL', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('MOTO_RF_OVER_NE', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('MOTO_RF_OVER_CAPITAL', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('MOTO_RF_OVER_NE', 'MOTO_REPLACEMENT', 'OPTIONAL', '30 diárias de moto reserva em caso de colisão, no valor de R$ 20,00 por dia', 10.00, 3),
    ('MOTO_RF_OVER_CAPITAL', 'MOTO_REPLACEMENT', 'OPTIONAL', '30 diárias de moto reserva em caso de colisão, no valor de R$ 20,00 por dia', 10.00, 3),
    ('MOTO_RF_OVER_NE', 'TOW_BREAKDOWN', 'OPTIONAL', 'Até 300 km por pane mecânica ou elétrica; 1 acionamento mensal e 6 anuais', 15.00, 4),
    ('MOTO_RF_OVER_CAPITAL', 'TOW_BREAKDOWN', 'OPTIONAL', 'Até 300 km por pane mecânica ou elétrica; 1 acionamento mensal e 6 anuais', 15.00, 4),
    ('MOTO_RF_OVER_NE', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão', NULL, 5),
    ('MOTO_RF_OVER_CAPITAL', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão', NULL, 5),
    ('MOTO_RF_OVER_NE', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 10 mil', NULL, 6),
    ('MOTO_RF_OVER_CAPITAL', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 10 mil', NULL, 6),
    ('MOTO_RF_OVER_NE', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 10 mil para danos ao veículo de terceiros', 10.00, 7),
    ('MOTO_RF_OVER_CAPITAL', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 10 mil para danos ao veículo de terceiros', 10.00, 7),
    ('MOTO_RF_OVER_NE', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 8),
    ('MOTO_RF_OVER_CAPITAL', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 8),
    ('MOTO_RF_OVER_NE', 'PARTICIPATION', 'INCLUDED', '10% com mínimo de R$ 2.000,00', NULL, 9),
    ('MOTO_RF_OVER_CAPITAL', 'PARTICIPATION', 'INCLUDED', '10% com mínimo de R$ 2.000,00', NULL, 9),
    ('MOTO_RF_OVER_NE', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 10),
    ('MOTO_RF_OVER_CAPITAL', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 10),
    ('MOTO_RF_OVER_NE', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 11),
    ('MOTO_RF_OVER_CAPITAL', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 11),
    ('MOTO_RF_OVER_NE', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 12),
    ('MOTO_RF_OVER_CAPITAL', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 12),
    ('MOTO_RF_OVER_NE', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 13),
    ('MOTO_RF_OVER_CAPITAL', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 13),
    ('MOTO_RF_OVER_NE', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 14),
    ('MOTO_RF_OVER_CAPITAL', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 14),
    ('CAR_ECONOMICO', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('CAR_ECONOMICO', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('CAR_ECONOMICO', 'COLLISION', 'INCLUDED', 'Colisão ou capotamento', NULL, 3),
    ('CAR_ECONOMICO', 'FIRE', 'INCLUDED', 'Incêndio derivado de colisão', NULL, 4),
    ('CAR_ECONOMICO', 'TOW_BREAKDOWN', 'INCLUDED', 'Até 500 km em caso de pane mecânica ou elétrica (250 km de ida e 250 km de volta)', NULL, 5),
    ('CAR_ECONOMICO', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão', NULL, 6),
    ('CAR_ECONOMICO', 'GLASS', 'INCLUDED', 'Cobertura de 50% para vidros', NULL, 7),
    ('CAR_ECONOMICO', 'TIRE', 'INCLUDED', 'Auxílio borracheiro', NULL, 8),
    ('CAR_ECONOMICO', 'LOCKSMITH', 'INCLUDED', 'Auxílio chaveiro de até R$ 150,00', NULL, 9),
    ('CAR_ECONOMICO', 'LODGING', 'INCLUDED', 'Auxílio hospedagem', NULL, 10),
    ('CAR_ECONOMICO', 'TAXI', 'INCLUDED', 'Auxílio táxi de até R$ 150,00', NULL, 11),
    ('CAR_ECONOMICO', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 35 mil', NULL, 12),
    ('CAR_ECONOMICO', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 50 mil para danos ao veículo de terceiros', 79.90, 13),
    ('CAR_ECONOMICO', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 14),
    ('CAR_ECONOMICO', 'PARTICIPATION', 'INCLUDED', '6% com mínimo de R$ 2.000,00; em roubo ou furto não há taxa de participação', NULL, 15),
    ('CAR_ECONOMICO', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 16),
    ('CAR_ECONOMICO', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 17),
    ('CAR_ECONOMICO', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 18),
    ('CAR_ECONOMICO', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 19),
    ('CAR_ECONOMICO', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 20),
    ('CAR_ECONOMICO', 'TRACKER', 'INCLUDED', 'Obrigatório para veículos a partir de R$ 200 mil', NULL, 21),
    ('CAR_COMPLETO', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('CAR_COMPLETO', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('CAR_COMPLETO', 'COLLISION', 'INCLUDED', 'Colisão ou capotamento', NULL, 3),
    ('CAR_COMPLETO', 'FIRE', 'INCLUDED', 'Incêndio', NULL, 4),
    ('CAR_COMPLETO', 'VEHICLE_REPLACEMENT', 'INCLUDED', '10 diárias de veículo reserva', NULL, 5),
    ('CAR_COMPLETO', 'TOW_BREAKDOWN', 'INCLUDED', 'Até 1.000 km em caso de pane mecânica ou elétrica', NULL, 6),
    ('CAR_COMPLETO', 'TOW_COLLISION', 'INCLUDED', 'Quilometragem livre em caso de colisão', NULL, 7),
    ('CAR_COMPLETO', 'GLASS', 'INCLUDED', 'Cobertura de 50% para vidros, ilimitada após o pagamento da terceira mensalidade', NULL, 8),
    ('CAR_COMPLETO', 'TIRE', 'INCLUDED', 'Auxílio borracheiro', NULL, 9),
    ('CAR_COMPLETO', 'LOCKSMITH', 'INCLUDED', 'Auxílio chaveiro de até R$ 150,00', NULL, 10),
    ('CAR_COMPLETO', 'LODGING', 'INCLUDED', 'Auxílio hospedagem', NULL, 11),
    ('CAR_COMPLETO', 'TAXI', 'INCLUDED', 'Auxílio táxi de até R$ 150,00', NULL, 12),
    ('CAR_COMPLETO', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 100 mil', NULL, 13),
    ('CAR_COMPLETO', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 50 mil para danos ao veículo de terceiros', 79.90, 14),
    ('CAR_COMPLETO', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 15),
    ('CAR_COMPLETO', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 2.000,00; em roubo ou furto não há taxa de participação', NULL, 16),
    ('CAR_COMPLETO', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 17),
    ('CAR_COMPLETO', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 18),
    ('CAR_COMPLETO', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 19),
    ('CAR_COMPLETO', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 20),
    ('CAR_COMPLETO', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 21),
    ('CAR_COMPLETO', 'TRACKER', 'INCLUDED', 'Obrigatório para veículos a partir de R$ 200 mil', NULL, 22),
    ('UTILITY_ECONOMICO', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('UTILITY_ECONOMICO', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('UTILITY_ECONOMICO', 'COLLISION', 'INCLUDED', 'Colisão ou capotamento', NULL, 3),
    ('UTILITY_ECONOMICO', 'FIRE', 'INCLUDED', 'Incêndio derivado de colisão', NULL, 4),
    ('UTILITY_ECONOMICO', 'TOW_BREAKDOWN', 'INCLUDED', 'Até 500 km em caso de pane mecânica ou elétrica', NULL, 5),
    ('UTILITY_ECONOMICO', 'TOW_COLLISION', 'INCLUDED', 'Quilometragem livre em caso de colisão', NULL, 6),
    ('UTILITY_ECONOMICO', 'GLASS', 'INCLUDED', 'Cobertura de 50% para vidros', NULL, 7),
    ('UTILITY_ECONOMICO', 'TIRE', 'INCLUDED', 'Auxílio borracheiro', NULL, 8),
    ('UTILITY_ECONOMICO', 'LOCKSMITH', 'INCLUDED', 'Auxílio chaveiro de até R$ 150,00', NULL, 9),
    ('UTILITY_ECONOMICO', 'LODGING', 'INCLUDED', 'Auxílio hospedagem', NULL, 10),
    ('UTILITY_ECONOMICO', 'TAXI', 'INCLUDED', 'Auxílio táxi de até R$ 150,00', NULL, 11),
    ('UTILITY_ECONOMICO', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 35 mil', NULL, 12),
    ('UTILITY_ECONOMICO', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 50 mil para danos ao veículo de terceiros', 79.90, 13),
    ('UTILITY_ECONOMICO', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 14),
    ('UTILITY_ECONOMICO', 'PARTICIPATION', 'INCLUDED', '6% com mínimo de R$ 2.000,00; em roubo ou furto não há taxa de participação', NULL, 15),
    ('UTILITY_ECONOMICO', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 16),
    ('UTILITY_ECONOMICO', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 17),
    ('UTILITY_ECONOMICO', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 18),
    ('UTILITY_ECONOMICO', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 19),
    ('UTILITY_ECONOMICO', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 20),
    ('UTILITY_ECONOMICO', 'TRACKER', 'INCLUDED', 'Obrigatório para veículos a partir de R$ 150 mil', NULL, 21),
    ('UTILITY_COMPLETO', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('UTILITY_COMPLETO', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('UTILITY_COMPLETO', 'COLLISION', 'INCLUDED', 'Colisão ou capotamento', NULL, 3),
    ('UTILITY_COMPLETO', 'FIRE', 'INCLUDED', 'Incêndio', NULL, 4),
    ('UTILITY_COMPLETO', 'VEHICLE_REPLACEMENT', 'INCLUDED', '10 diárias de veículo reserva', NULL, 5),
    ('UTILITY_COMPLETO', 'TOW_BREAKDOWN', 'INCLUDED', 'Até 1.000 km em caso de pane mecânica ou elétrica', NULL, 6),
    ('UTILITY_COMPLETO', 'TOW_COLLISION', 'INCLUDED', 'Quilometragem livre em caso de colisão', NULL, 7),
    ('UTILITY_COMPLETO', 'GLASS', 'INCLUDED', 'Cobertura de 50% para vidros, ilimitada após o pagamento da terceira mensalidade', NULL, 8),
    ('UTILITY_COMPLETO', 'TIRE', 'INCLUDED', 'Auxílio borracheiro', NULL, 9),
    ('UTILITY_COMPLETO', 'LOCKSMITH', 'INCLUDED', 'Auxílio chaveiro de até R$ 150,00', NULL, 10),
    ('UTILITY_COMPLETO', 'LODGING', 'INCLUDED', 'Auxílio hospedagem', NULL, 11),
    ('UTILITY_COMPLETO', 'TAXI', 'INCLUDED', 'Auxílio táxi de até R$ 150,00', NULL, 12),
    ('UTILITY_COMPLETO', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 100 mil', NULL, 13),
    ('UTILITY_COMPLETO', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 50 mil para danos ao veículo de terceiros', 79.90, 14),
    ('UTILITY_COMPLETO', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 15),
    ('UTILITY_COMPLETO', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 2.000,00; em roubo ou furto não há taxa de participação', NULL, 16),
    ('UTILITY_COMPLETO', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 17),
    ('UTILITY_COMPLETO', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 18),
    ('UTILITY_COMPLETO', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 19),
    ('UTILITY_COMPLETO', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 20),
    ('UTILITY_COMPLETO', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 21),
    ('UTILITY_COMPLETO', 'TRACKER', 'INCLUDED', 'Obrigatório para veículos a partir de R$ 200 mil', NULL, 22),
    ('CAR_IMPORTED', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('CAR_IMPORTED', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('CAR_IMPORTED', 'TOW_BREAKDOWN', 'INCLUDED', 'Até 500 km em caso de pane mecânica ou elétrica', NULL, 3),
    ('CAR_IMPORTED', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão', NULL, 4),
    ('CAR_IMPORTED', 'TIRE', 'INCLUDED', 'Auxílio borracheiro', NULL, 5),
    ('CAR_IMPORTED', 'LOCKSMITH', 'INCLUDED', 'Auxílio chaveiro de até R$ 150,00', NULL, 6),
    ('CAR_IMPORTED', 'LODGING', 'INCLUDED', 'Auxílio hospedagem', NULL, 7),
    ('CAR_IMPORTED', 'TAXI', 'INCLUDED', 'Auxílio táxi de até R$ 150,00', NULL, 8),
    ('CAR_IMPORTED', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 100 mil', NULL, 9),
    ('CAR_IMPORTED', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 50 mil para danos ao veículo de terceiros', 79.90, 10),
    ('CAR_IMPORTED', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 11),
    ('CAR_IMPORTED', 'PARTICIPATION', 'INCLUDED', '6% com mínimo de R$ 2.000,00', NULL, 12),
    ('CAR_IMPORTED', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 13),
    ('CAR_IMPORTED', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 14),
    ('CAR_IMPORTED', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 15),
    ('CAR_IMPORTED', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 16),
    ('CAR_IMPORTED', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 17),
    ('CAR_IMPORTED', 'TRACKER', 'INCLUDED', 'Obrigatório para veículos a partir de R$ 200 mil', NULL, 18),
    ('TRUCK_OURO_SDT', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('TRUCK_OURO_SDT', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('TRUCK_OURO_SDT', 'COLLISION', 'INCLUDED', 'Colisão ou capotamento', NULL, 3),
    ('TRUCK_OURO_SDT', 'FIRE', 'INCLUDED', 'Incêndio derivado de colisão', NULL, 4),
    ('TRUCK_OURO_SDT', 'TOTAL_LOSS', 'INCLUDED', NULL, NULL, 5),
    ('TRUCK_OURO_SDT', 'TOW_BREAKDOWN', 'INCLUDED', 'Até 300 km; 1 acionamento mensal por pane elétrica ou mecânica', NULL, 6),
    ('TRUCK_OURO_SDT', 'TOW_COLLISION', 'INCLUDED', 'Quilometragem livre em caso de colisão', NULL, 7),
    ('TRUCK_OURO_SDT', 'LODGING', 'INCLUDED', 'Auxílio hospedagem', NULL, 8),
    ('TRUCK_OURO_SDT', 'THIRD_PARTY', 'OPTIONAL', 'Cobertura de até R$ 50 mil para danos ao veículo de terceiros', 79.90, 9),
    ('TRUCK_OURO_SDT', 'GLASS', 'INCLUDED', 'Cobertura de 50% para vidros; 1 acionamento por ano', NULL, 10),
    ('TRUCK_OURO_SDT', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 11),
    ('TRUCK_OURO_SDT', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 6.000,00; em roubo ou furto não há taxa de participação', NULL, 12),
    ('TRUCK_OURO_SDT', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 13),
    ('TRUCK_OURO_SDT', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 14),
    ('TRUCK_OURO_SDT', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 15),
    ('TRUCK_OURO_SDT', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 16),
    ('TRUCK_OURO_SDT', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 17),
    ('TRUCK_OURO_SDT', 'TRACKER', 'INCLUDED', 'Obrigatório para veículos a partir de R$ 150 mil; instalação de R$ 200,00 e R$ 20,00 por parcela', NULL, 18),
    ('TRUCK_OURO_PLUS', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('TRUCK_OURO_PLUS', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('TRUCK_OURO_PLUS', 'COLLISION', 'INCLUDED', 'Colisão ou capotamento', NULL, 3),
    ('TRUCK_OURO_PLUS', 'FIRE', 'INCLUDED', 'Incêndio', NULL, 4),
    ('TRUCK_OURO_PLUS', 'TOTAL_LOSS', 'INCLUDED', NULL, NULL, 5),
    ('TRUCK_OURO_PLUS', 'TOW_BREAKDOWN', 'INCLUDED', 'Até 500 km; 1 acionamento mensal por pane elétrica ou mecânica', NULL, 6),
    ('TRUCK_OURO_PLUS', 'TOW_COLLISION', 'INCLUDED', 'Quilometragem livre em caso de colisão', NULL, 7),
    ('TRUCK_OURO_PLUS', 'LODGING', 'INCLUDED', 'Auxílio hospedagem', NULL, 8),
    ('TRUCK_OURO_PLUS', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de R$ 50 mil para danos ao veículo de terceiros', NULL, 9),
    ('TRUCK_OURO_PLUS', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 50 mil para danos ao veículo de terceiros', 79.90, 10),
    ('TRUCK_OURO_PLUS', 'GLASS', 'INCLUDED', 'Cobertura de 50% para vidros; 1 acionamento por ano', NULL, 11),
    ('TRUCK_OURO_PLUS', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 12),
    ('TRUCK_OURO_PLUS', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 6.000,00; em roubo ou furto não há taxa de participação', NULL, 13),
    ('TRUCK_OURO_PLUS', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 14),
    ('TRUCK_OURO_PLUS', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 15),
    ('TRUCK_OURO_PLUS', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 16),
    ('TRUCK_OURO_PLUS', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 17),
    ('TRUCK_OURO_PLUS', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 18),
    ('TRUCK_OURO_PLUS', 'TRACKER', 'INCLUDED', 'Obrigatório para veículos a partir de R$ 150 mil; instalação de R$ 200,00 e R$ 20,00 por parcela', NULL, 19),
    ('TRUCK_DIAMANTE_PLUS', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('TRUCK_DIAMANTE_PLUS', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('TRUCK_DIAMANTE_PLUS', 'COLLISION', 'INCLUDED', 'Colisão ou capotamento', NULL, 3),
    ('TRUCK_DIAMANTE_PLUS', 'FIRE', 'INCLUDED', 'Incêndio', NULL, 4),
    ('TRUCK_DIAMANTE_PLUS', 'TOTAL_LOSS', 'INCLUDED', NULL, NULL, 5),
    ('TRUCK_DIAMANTE_PLUS', 'NATIONAL', 'INCLUDED', 'Cobertura nacional', NULL, 6),
    ('TRUCK_DIAMANTE_PLUS', 'ASSISTANCE_24H', 'INCLUDED', 'Assistência 24 horas', NULL, 7),
    ('TRUCK_DIAMANTE_PLUS', 'TOW_BREAKDOWN', 'INCLUDED', 'Até 1.000 km; 1 acionamento mensal por pane elétrica ou mecânica', NULL, 8),
    ('TRUCK_DIAMANTE_PLUS', 'TOW_COLLISION', 'INCLUDED', 'Quilometragem livre em caso de colisão', NULL, 9),
    ('TRUCK_DIAMANTE_PLUS', 'LODGING', 'INCLUDED', 'Auxílio hospedagem', NULL, 10),
    ('TRUCK_DIAMANTE_PLUS', 'THIRD_PARTY_BASE', 'INCLUDED', 'Cobertura de até R$ 100 mil para danos ao veículo de terceiros', NULL, 11),
    ('TRUCK_DIAMANTE_PLUS', 'THIRD_PARTY', 'OPTIONAL', 'Adicional de mais R$ 50 mil para danos ao veículo de terceiros', 79.90, 12),
    ('TRUCK_DIAMANTE_PLUS', 'GLASS', 'INCLUDED', 'Cobertura de 50% para vidros; 1 acionamento por ano', NULL, 13),
    ('TRUCK_DIAMANTE_PLUS', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 14),
    ('TRUCK_DIAMANTE_PLUS', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 6.000,00; em roubo ou furto não há taxa de participação', NULL, 15),
    ('TRUCK_DIAMANTE_PLUS', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 16),
    ('TRUCK_DIAMANTE_PLUS', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 17),
    ('TRUCK_DIAMANTE_PLUS', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 18),
    ('TRUCK_DIAMANTE_PLUS', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 19),
    ('TRUCK_DIAMANTE_PLUS', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 20),
    ('TRUCK_DIAMANTE_PLUS', 'TRACKER', 'INCLUDED', 'Obrigatório para veículos a partir de R$ 150 mil; instalação de R$ 200,00 e R$ 20,00 por parcela', NULL, 21),
    ('MOTO_SCOOTER_ELECTRIC', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('MOTO_SCOOTER_ELECTRIC', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('MOTO_SCOOTER_ELECTRIC', 'TOW_COLLISION', 'INCLUDED', 'Até 50 km em caso de colisão (25 km de ida e 25 km de volta)', NULL, 3),
    ('MOTO_SCOOTER_ELECTRIC', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 4),
    ('MOTO_SCOOTER_ELECTRIC', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 600,00', NULL, 5),
    ('MOTO_SCOOTER_ELECTRIC', 'FUNERAL', 'OPTIONAL', 'Auxílio funeral individual de R$ 3.000,00', 5.00, 6),
    ('MOTO_SCOOTER_ELECTRIC', 'FUNERAL_FAMILY', 'OPTIONAL', 'Auxílio funeral familiar de R$ 3.000,00 por pessoa, conforme regras do plano', 12.00, 7),
    ('MOTO_SCOOTER_ELECTRIC', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 8),
    ('MOTO_SCOOTER_ELECTRIC', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 9),
    ('MOTO_SCOOTER_ELECTRIC', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 10),
    ('MOTO_PROMO_2026', 'ROBBERY', 'INCLUDED', NULL, NULL, 1),
    ('MOTO_PROMO_2026', 'THEFT', 'INCLUDED', NULL, NULL, 2),
    ('MOTO_PROMO_2026', 'COLLISION', 'INCLUDED', 'Colisão ou queda', NULL, 3),
    ('MOTO_PROMO_2026', 'FIRE', 'INCLUDED', 'Incêndio', NULL, 4),
    ('MOTO_PROMO_2026', 'TOTAL_LOSS', 'INCLUDED', NULL, NULL, 5),
    ('MOTO_PROMO_2026', 'TOW_COLLISION', 'INCLUDED', 'Até 1.000 km em caso de colisão (500 km de ida e 500 km de volta)', NULL, 6),
    ('MOTO_PROMO_2026', 'NO_CREDIT_CHECK', 'INCLUDED', 'Sem consulta ao SPC e Serasa', NULL, 7),
    ('MOTO_PROMO_2026', 'PARTICIPATION', 'INCLUDED', '7% com mínimo de R$ 600,00; em roubo ou furto não há taxa de participação', NULL, 8),
    ('MOTO_PROMO_2026', 'SAMVIDA', 'INCLUDED', 'Assistência médica SAMVIDA', NULL, 9),
    ('MOTO_PROMO_2026', 'PHARMACY', 'INCLUDED', 'Desconto de até 30% em medicamentos nas Drogarias Sampaio', NULL, 10),
    ('MOTO_PROMO_2026', 'CLUB', 'INCLUDED', 'Clube de vantagens', NULL, 11)
) AS data(plan_code, coverage_code, status, detail, monthly_price, sort_order)
JOIN plans p ON p.code = data.plan_code
JOIN coverages c ON c.code = data.coverage_code;

-- Mantém os planos de scooter/elétrica e promocional desativados até o cadastro das respectivas tabelas de preços.
UPDATE plans SET active = FALSE WHERE code IN ('MOTO_SCOOTER_ELECTRIC', 'MOTO_PROMO_2026');
