
CREATE TABLE consultants (
    id UUID PRIMARY KEY,
    name VARCHAR(140) NOT NULL,
    normalized_name VARCHAR(160) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    source VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

ALTER TABLE quotations ALTER COLUMN consultant_name TYPE VARCHAR(140);
ALTER TABLE quotations ADD COLUMN consultant_id UUID REFERENCES consultants(id);
ALTER TABLE quotations ADD COLUMN valid_until TIMESTAMPTZ;
UPDATE quotations SET valid_until = created_at + INTERVAL '5 days' WHERE valid_until IS NULL;
ALTER TABLE quotations ALTER COLUMN valid_until SET NOT NULL;

CREATE INDEX idx_consultants_active_name ON consultants(active, name);
CREATE INDEX idx_quotations_consultant ON quotations(consultant_id);
CREATE INDEX idx_quotations_valid_until ON quotations(valid_until);

CREATE TEMP TABLE seed_consultants(name VARCHAR(140), active BOOLEAN, source VARCHAR(30));
INSERT INTO seed_consultants(name, active, source) VALUES
('GENIVAL SANTOS SILVA', TRUE, 'IMPORTED'),
('LEONARDO SIMOES NOGUEIRA', TRUE, 'IMPORTED'),
('JOSE MAURICIO FERNANDO CORREIA', TRUE, 'IMPORTED'),
('ALEXANDRE NETO DA SILVA', TRUE, 'IMPORTED'),
('LUIS PHELLIPE DE LIMA AZEVEDO', TRUE, 'IMPORTED'),
('VALMERIO DA SILVA', TRUE, 'IMPORTED'),
('ANTONIO BULHOES DE OLIVEIRA NETO', TRUE, 'IMPORTED'),
('JOSE DE SOUZA SANTOS', TRUE, 'IMPORTED'),
('FRANKUT JOSE DA SILVA', TRUE, 'IMPORTED'),
('JOSE GABRIEL DOS SANTOS', TRUE, 'IMPORTED'),
('CLEYTON DE ALMEIDA SILVA', TRUE, 'IMPORTED'),
('ARNOBIO PHELIPE SANTOS', TRUE, 'IMPORTED'),
('ROMERSOM SOARES ARAUJO DA SILVA', TRUE, 'IMPORTED'),
('MARCELO HENRIQUE DA SILVA', TRUE, 'IMPORTED'),
('RONILVO CARAÍBA DA SILVA', TRUE, 'IMPORTED'),
('CARLOS JOSE DOS SANTOS', TRUE, 'IMPORTED'),
('EDIVAN PEREIRA DA SILVA', TRUE, 'IMPORTED'),
('RENATO SILVA DOS SANTOS', TRUE, 'IMPORTED'),
('MARCIO DE MELO RIBEIRO', TRUE, 'IMPORTED'),
('ADEMIR FERREIRA DOS SANTOS', TRUE, 'IMPORTED'),
('CICERO DA SILVA ROCHA', TRUE, 'IMPORTED'),
('WELLINGTON SILVA DE LIMA', TRUE, 'IMPORTED'),
('JAMES CLEITON CARMO DE ARAUJO', TRUE, 'IMPORTED'),
('RODRIGO LIMA DOS SANTOS', TRUE, 'IMPORTED'),
('CLAUDIONOR DE MORAIS', TRUE, 'IMPORTED'),
('VALTERLANGER ALVES DOS SATOS', TRUE, 'IMPORTED'),
('CELSO PEREIRA SILVA FILHO', TRUE, 'IMPORTED'),
('BRUNO BARROS LEITE', TRUE, 'IMPORTED'),
('CARLOS JORGE DE AMORIM SILVA', TRUE, 'IMPORTED'),
('EDIVALDO PROCOPIO DA COSTA', TRUE, 'IMPORTED'),
('GILMARIO DE OLIVEIRA DA SILVA', TRUE, 'IMPORTED'),
('JOAO PEDRO TERTO DA SILVA', TRUE, 'IMPORTED'),
('ALLISON MINELI ALBUQUERQUE DE SOUZA', TRUE, 'IMPORTED'),
('JOSE CARLOS DA SILVA', TRUE, 'IMPORTED'),
('JOSE EDUARDO PINTO DA SILVA', TRUE, 'IMPORTED'),
('RENILDO JOSE APOLINARIO', TRUE, 'IMPORTED'),
('SERGIO DOS SANTOS', TRUE, 'IMPORTED'),
('LUIZ CARLOS ARAÚJO DOS SANTOS', TRUE, 'IMPORTED'),
('PEDRO EMANUEL DOS SANTOS PETRUCIO', TRUE, 'IMPORTED'),
('VAGNER SILVA NASCIMENTO', TRUE, 'IMPORTED'),
('JOSE CICERO BATISTA DA SILVA', TRUE, 'IMPORTED'),
('ANGELO DANILO SOARES BARROS', TRUE, 'IMPORTED'),
('LUCAS MATOS SOBRAL', TRUE, 'IMPORTED'),
('EVERALDO LEONARDO DE OLIVEIRA', TRUE, 'IMPORTED'),
('ROMULO RIBEIRO DA SILVA', TRUE, 'IMPORTED');

INSERT INTO consultants(id, name, normalized_name, active, source, created_at, updated_at)
SELECT gen_random_uuid(),
       name,
       lower(trim(regexp_replace(translate(name,
         'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑ',
         'AAAAAEEEEIIIIOOOOOUUUUCN'), '[^A-Za-z0-9]+', ' ', 'g'))),
       active, source, now(), now()
FROM seed_consultants
ON CONFLICT (normalized_name) DO NOTHING;
