-- V64 - Perfil detalhado do veículo/plano e checklist técnico completo por categoria.
-- Mantém as quatro categorias operacionais solicitadas: motocicleta, carro leve, utilitário e caminhão/veículo pesado.
ALTER TABLE nh_event_records
    ADD COLUMN IF NOT EXISTS plan_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS plan_monthly_amount NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS participation_amount NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS coverage_notes TEXT,
    ADD COLUMN IF NOT EXISTS vehicle_brand VARCHAR(120),
    ADD COLUMN IF NOT EXISTS vehicle_version VARCHAR(180),
    ADD COLUMN IF NOT EXISTS vehicle_subtype VARCHAR(80),
    ADD COLUMN IF NOT EXISTS vehicle_fuel VARCHAR(60),
    ADD COLUMN IF NOT EXISTS vehicle_transmission VARCHAR(60),
    ADD COLUMN IF NOT EXISTS vehicle_odometer BIGINT,
    ADD COLUMN IF NOT EXISTS fipe_code VARCHAR(40),
    ADD COLUMN IF NOT EXISTS fipe_value NUMERIC(14,2);
ALTER TABLE nh_event_records DROP CONSTRAINT IF EXISTS ck_nh_event_plan_monthly_amount;
ALTER TABLE nh_event_records ADD CONSTRAINT ck_nh_event_plan_monthly_amount CHECK (plan_monthly_amount IS NULL OR plan_monthly_amount >= 0);
ALTER TABLE nh_event_records DROP CONSTRAINT IF EXISTS ck_nh_event_participation_amount;
ALTER TABLE nh_event_records ADD CONSTRAINT ck_nh_event_participation_amount CHECK (participation_amount IS NULL OR participation_amount >= 0);
ALTER TABLE nh_event_records DROP CONSTRAINT IF EXISTS ck_nh_event_vehicle_odometer;
ALTER TABLE nh_event_records ADD CONSTRAINT ck_nh_event_vehicle_odometer CHECK (vehicle_odometer IS NULL OR vehicle_odometer >= 0);
ALTER TABLE nh_event_records DROP CONSTRAINT IF EXISTS ck_nh_event_fipe_value;
ALTER TABLE nh_event_records ADD CONSTRAINT ck_nh_event_fipe_value CHECK (fipe_value IS NULL OR fipe_value >= 0);

-- A oficina passa a usar somente os templates ativos desta versão.
UPDATE nh_event_checklist_template_items SET active=FALSE, updated_at=NOW() WHERE vehicle_category IN ('MOTORCYCLE','LIGHT_CAR','UTILITY','TRUCK');

-- Checklist completo: MOTORCYCLE
INSERT INTO nh_event_checklist_template_items(id,vehicle_category,section,label,sort_order,active)
SELECT gen_random_uuid(), 'MOTORCYCLE', x.section, x.label, x.ord, TRUE
FROM (VALUES
 ('Dianteira e comandos','Farol principal',10),
 ('Dianteira e comandos','Carenagem/Painel frontal',11),
 ('Dianteira e comandos','Bolha/Para-brisa',12),
 ('Dianteira e comandos','Guidão',13),
 ('Dianteira e comandos','Mesa superior',14),
 ('Dianteira e comandos','Mesa inferior',15),
 ('Dianteira e comandos','Manopla direita',16),
 ('Dianteira e comandos','Manopla esquerda',17),
 ('Dianteira e comandos','Manete de freio',18),
 ('Dianteira e comandos','Manete de embreagem',19),
 ('Dianteira e comandos','Retrovisor direito',20),
 ('Dianteira e comandos','Retrovisor esquerdo',21),
 ('Dianteira e comandos','Comando elétrico direito',22),
 ('Dianteira e comandos','Comando elétrico esquerdo',23),
 ('Dianteira e comandos','Painel de instrumentos',24),
 ('Suspensão e direção','Bengala/Garfo direito',40),
 ('Suspensão e direção','Bengala/Garfo esquerdo',41),
 ('Suspensão e direção','Retentor do garfo direito',42),
 ('Suspensão e direção','Retentor do garfo esquerdo',43),
 ('Suspensão e direção','Eixo da roda dianteira',44),
 ('Suspensão e direção','Rolamento da direção',45),
 ('Suspensão e direção','Amortecedor de direção (quando aplicável)',46),
 ('Roda e freio dianteiro','Roda dianteira',60),
 ('Roda e freio dianteiro','Pneu dianteiro',61),
 ('Roda e freio dianteiro','Disco de freio dianteiro',62),
 ('Roda e freio dianteiro','Pinça de freio dianteira',63),
 ('Roda e freio dianteiro','Cilindro mestre dianteiro',64),
 ('Roda e freio dianteiro','Mangueira de freio dianteira',65),
 ('Roda e freio dianteiro','Sensor ABS dianteiro',66),
 ('Roda e freio dianteiro','Anel fônico ABS dianteiro',67),
 ('Lateral direita','Carenagem lateral direita',80),
 ('Lateral direita','Tampa lateral direita',81),
 ('Lateral direita','Pedaleira dianteira direita',82),
 ('Lateral direita','Pedaleira traseira direita',83),
 ('Lateral direita','Pedal do freio traseiro',84),
 ('Lateral direita','Protetor de motor direito',85),
 ('Lateral direita','Escapamento/Ponteira',86),
 ('Lateral direita','Curva/Coletor de escape',87),
 ('Lateral esquerda','Carenagem lateral esquerda',100),
 ('Lateral esquerda','Tampa lateral esquerda',101),
 ('Lateral esquerda','Pedaleira dianteira esquerda',102),
 ('Lateral esquerda','Pedaleira traseira esquerda',103),
 ('Lateral esquerda','Pedal/Câmbio de marchas',104),
 ('Lateral esquerda','Protetor de motor esquerdo',105),
 ('Lateral esquerda','Cavalete lateral',106),
 ('Lateral esquerda','Cavalete central (quando aplicável)',107),
 ('Centro e estrutura','Tanque de combustível',120),
 ('Centro e estrutura','Tampa do tanque',121),
 ('Centro e estrutura','Banco do piloto',122),
 ('Centro e estrutura','Banco do garupa',123),
 ('Centro e estrutura','Chassi/Quadro principal',124),
 ('Centro e estrutura','Subchassi traseiro',125),
 ('Centro e estrutura','Suporte do motor',126),
 ('Centro e estrutura','Protetor inferior/Cárter',127),
 ('Traseira e suspensão','Rabeta',150),
 ('Traseira e suspensão','Paralama traseiro',151),
 ('Traseira e suspensão','Suporte de placa',152),
 ('Traseira e suspensão','Lanterna traseira',153),
 ('Traseira e suspensão','Piscas traseiros',154),
 ('Traseira e suspensão','Alça do garupa/Bauleto suporte',155),
 ('Traseira e suspensão','Balança traseira',156),
 ('Traseira e suspensão','Amortecedor traseiro direito',157),
 ('Traseira e suspensão','Amortecedor traseiro esquerdo/Monochoque',158),
 ('Traseira e suspensão','Link da suspensão traseira',159),
 ('Traseira e suspensão','Eixo da roda traseira',160),
 ('Roda e freio traseiro','Roda traseira',180),
 ('Roda e freio traseiro','Pneu traseiro',181),
 ('Roda e freio traseiro','Disco/Tambor de freio traseiro',182),
 ('Roda e freio traseiro','Pinça de freio traseira',183),
 ('Roda e freio traseiro','Cilindro mestre traseiro',184),
 ('Roda e freio traseiro','Mangueira de freio traseira',185),
 ('Roda e freio traseiro','Sensor ABS traseiro',186),
 ('Roda e freio traseiro','Anel fônico ABS traseiro',187),
 ('Motor e alimentação','Motor/Bloco',210),
 ('Motor e alimentação','Cabeçote',211),
 ('Motor e alimentação','Tampa do cabeçote',212),
 ('Motor e alimentação','Cárter',213),
 ('Motor e alimentação','Radiador (quando líquido)',214),
 ('Motor e alimentação','Ventoinha (quando aplicável)',215),
 ('Motor e alimentação','Mangueiras de arrefecimento',216),
 ('Motor e alimentação','Reservatório de expansão',217),
 ('Motor e alimentação','Sistema de injeção/Carburador',218),
 ('Motor e alimentação','Corpo de borboleta',219),
 ('Motor e alimentação','Bomba de combustível',220),
 ('Motor e alimentação','Filtro/Caixa de ar',221),
 ('Motor e alimentação','Tanque de combustível — estrutura',222),
 ('Motor e alimentação','Coxins/Suportes do motor',223),
 ('Transmissão','Embreagem',240),
 ('Transmissão','Câmbio',241),
 ('Transmissão','Corrente de transmissão',242),
 ('Transmissão','Coroa',243),
 ('Transmissão','Pinhão',244),
 ('Transmissão','Correia de transmissão (quando aplicável)',245),
 ('Transmissão','Cardã/Diferencial (quando aplicável)',246),
 ('Transmissão','Capa/Protetor de corrente',247),
 ('Elétrica e eletrônica','Bateria 12V',270),
 ('Elétrica e eletrônica','Estator/Alternador',271),
 ('Elétrica e eletrônica','Motor de partida',272),
 ('Elétrica e eletrônica','Retificador/Regulador',273),
 ('Elétrica e eletrônica','ECU/Módulo de injeção',274),
 ('Elétrica e eletrônica','Módulo ABS',275),
 ('Elétrica e eletrônica','Chicote principal',276),
 ('Elétrica e eletrônica','Caixa de fusíveis',277),
 ('Elétrica e eletrônica','Bobina de ignição',278),
 ('Elétrica e eletrônica','Farol/Driver LED',279),
 ('Elétrica e eletrônica','Piscas dianteiros',280),
 ('Elétrica e eletrônica','Buzina',281),
 ('Elétrica e eletrônica','Sensor de descanso lateral',282),
 ('Elétrica e eletrônica','Sensor de queda/inclinação',283),
 ('Segurança e acessórios','Sistema ABS',310),
 ('Segurança e acessórios','Controle de tração (quando aplicável)',311),
 ('Segurança e acessórios','Chave/Ignição',312),
 ('Segurança e acessórios','Imobilizador',313),
 ('Segurança e acessórios','Alarme/Rastreador instalado',314),
 ('Segurança e acessórios','Protetor de mãos',315),
 ('Segurança e acessórios','Mata-cachorro/Protetor de motor',316),
 ('Segurança e acessórios','Bauleto/Bagageiro',317),
 ('Segurança e acessórios','Suporte de celular/Multimídia',318),
 ('Elétrica — motocicleta elétrica quando aplicável','Bateria de tração',340),
 ('Elétrica — motocicleta elétrica quando aplicável','Caixa da bateria de tração',341),
 ('Elétrica — motocicleta elétrica quando aplicável','Cabos de alta tensão',342),
 ('Elétrica — motocicleta elétrica quando aplicável','Controlador/Inversor',343),
 ('Elétrica — motocicleta elétrica quando aplicável','Motor elétrico',344),
 ('Elétrica — motocicleta elétrica quando aplicável','Porta/Conector de recarga',345),
 ('Elétrica — motocicleta elétrica quando aplicável','Carregador embarcado',346),
 ('Elétrica — motocicleta elétrica quando aplicável','Conversor DC-DC',347)
) AS x(section,label,ord)
ON CONFLICT (vehicle_category,label) DO UPDATE
SET section=EXCLUDED.section, sort_order=EXCLUDED.sort_order, active=TRUE, updated_at=NOW();

-- Checklist completo: LIGHT_CAR
INSERT INTO nh_event_checklist_template_items(id,vehicle_category,section,label,sort_order,active)
SELECT gen_random_uuid(), 'LIGHT_CAR', x.section, x.label, x.ord, TRUE
FROM (VALUES
 ('Identificação e carroceria dianteira','Para-choque dianteiro',10),
 ('Identificação e carroceria dianteira','Alma do para-choque dianteiro',11),
 ('Identificação e carroceria dianteira','Absorvedor do para-choque dianteiro',12),
 ('Identificação e carroceria dianteira','Grade frontal',13),
 ('Identificação e carroceria dianteira','Capô',14),
 ('Identificação e carroceria dianteira','Fechadura do capô',15),
 ('Identificação e carroceria dianteira','Dobradiça do capô direita',16),
 ('Identificação e carroceria dianteira','Dobradiça do capô esquerda',17),
 ('Identificação e carroceria dianteira','Painel frontal',18),
 ('Identificação e carroceria dianteira','Travessa superior dianteira',19),
 ('Identificação e carroceria dianteira','Travessa inferior dianteira',20),
 ('Identificação e carroceria dianteira','Farol direito',21),
 ('Identificação e carroceria dianteira','Farol esquerdo',22),
 ('Identificação e carroceria dianteira','Farol de neblina direito',23),
 ('Identificação e carroceria dianteira','Farol de neblina esquerdo',24),
 ('Identificação e carroceria dianteira','DRL/Luz diurna direita',25),
 ('Identificação e carroceria dianteira','DRL/Luz diurna esquerda',26),
 ('Identificação e carroceria dianteira','Para-lama dianteiro direito',27),
 ('Identificação e carroceria dianteira','Para-lama dianteiro esquerdo',28),
 ('Identificação e carroceria dianteira','Parabarro dianteiro direito',29),
 ('Identificação e carroceria dianteira','Parabarro dianteiro esquerdo',30),
 ('Carroceria lateral direita','Retrovisor direito',40),
 ('Carroceria lateral direita','Capa do retrovisor direito',41),
 ('Carroceria lateral direita','Pisca do retrovisor direito',42),
 ('Carroceria lateral direita','Porta dianteira direita',43),
 ('Carroceria lateral direita','Dobradiças da porta dianteira direita',44),
 ('Carroceria lateral direita','Fechadura da porta dianteira direita',45),
 ('Carroceria lateral direita','Maçaneta da porta dianteira direita',46),
 ('Carroceria lateral direita','Porta traseira direita',47),
 ('Carroceria lateral direita','Dobradiças da porta traseira direita',48),
 ('Carroceria lateral direita','Fechadura da porta traseira direita',49),
 ('Carroceria lateral direita','Maçaneta da porta traseira direita',50),
 ('Carroceria lateral direita','Caixa de ar direita',51),
 ('Carroceria lateral direita','Coluna A direita',52),
 ('Carroceria lateral direita','Coluna B direita',53),
 ('Carroceria lateral direita','Coluna C direita',54),
 ('Carroceria lateral direita','Lateral traseira direita',55),
 ('Carroceria lateral esquerda','Retrovisor esquerdo',70),
 ('Carroceria lateral esquerda','Capa do retrovisor esquerdo',71),
 ('Carroceria lateral esquerda','Pisca do retrovisor esquerdo',72),
 ('Carroceria lateral esquerda','Porta dianteira esquerda',73),
 ('Carroceria lateral esquerda','Dobradiças da porta dianteira esquerda',74),
 ('Carroceria lateral esquerda','Fechadura da porta dianteira esquerda',75),
 ('Carroceria lateral esquerda','Maçaneta da porta dianteira esquerda',76),
 ('Carroceria lateral esquerda','Porta traseira esquerda',77),
 ('Carroceria lateral esquerda','Dobradiças da porta traseira esquerda',78),
 ('Carroceria lateral esquerda','Fechadura da porta traseira esquerda',79),
 ('Carroceria lateral esquerda','Maçaneta da porta traseira esquerda',80),
 ('Carroceria lateral esquerda','Caixa de ar esquerda',81),
 ('Carroceria lateral esquerda','Coluna A esquerda',82),
 ('Carroceria lateral esquerda','Coluna B esquerda',83),
 ('Carroceria lateral esquerda','Coluna C esquerda',84),
 ('Carroceria lateral esquerda','Lateral traseira esquerda',85),
 ('Traseira e compartimento de bagagem','Para-choque traseiro',100),
 ('Traseira e compartimento de bagagem','Alma do para-choque traseiro',101),
 ('Traseira e compartimento de bagagem','Absorvedor do para-choque traseiro',102),
 ('Traseira e compartimento de bagagem','Tampa traseira/Porta-malas',103),
 ('Traseira e compartimento de bagagem','Dobradiças da tampa traseira',104),
 ('Traseira e compartimento de bagagem','Fechadura da tampa traseira',105),
 ('Traseira e compartimento de bagagem','Lanterna traseira direita',106),
 ('Traseira e compartimento de bagagem','Lanterna traseira esquerda',107),
 ('Traseira e compartimento de bagagem','Luz de placa',108),
 ('Traseira e compartimento de bagagem','Painel traseiro',109),
 ('Traseira e compartimento de bagagem','Assoalho do porta-malas',110),
 ('Traseira e compartimento de bagagem','Estepe/Alojamento do estepe',111),
 ('Vidros, teto e acabamentos externos','Para-brisa',130),
 ('Vidros, teto e acabamentos externos','Vidro traseiro',131),
 ('Vidros, teto e acabamentos externos','Vidro dianteiro direito',132),
 ('Vidros, teto e acabamentos externos','Vidro dianteiro esquerdo',133),
 ('Vidros, teto e acabamentos externos','Vidro traseiro direito',134),
 ('Vidros, teto e acabamentos externos','Vidro traseiro esquerdo',135),
 ('Vidros, teto e acabamentos externos','Teto',136),
 ('Vidros, teto e acabamentos externos','Longarina de teto direita',137),
 ('Vidros, teto e acabamentos externos','Longarina de teto esquerda',138),
 ('Vidros, teto e acabamentos externos','Calha/Moldura de teto',139),
 ('Vidros, teto e acabamentos externos','Teto solar/Panorâmico',140),
 ('Vidros, teto e acabamentos externos','Palhetas e braços do limpador dianteiro',141),
 ('Vidros, teto e acabamentos externos','Motor do limpador dianteiro',142),
 ('Vidros, teto e acabamentos externos','Esguichadores do para-brisa',143),
 ('Estrutural','Longarina dianteira direita',160),
 ('Estrutural','Longarina dianteira esquerda',161),
 ('Estrutural','Longarina traseira direita',162),
 ('Estrutural','Longarina traseira esquerda',163),
 ('Estrutural','Travessa dianteira',164),
 ('Estrutural','Travessa central',165),
 ('Estrutural','Travessa traseira',166),
 ('Estrutural','Assoalho dianteiro',167),
 ('Estrutural','Assoalho central',168),
 ('Estrutural','Assoalho traseiro',169),
 ('Estrutural','Painel corta-fogo',170),
 ('Estrutural','Caixa de roda dianteira direita',171),
 ('Estrutural','Caixa de roda dianteira esquerda',172),
 ('Estrutural','Caixa de roda traseira direita',173),
 ('Estrutural','Caixa de roda traseira esquerda',174),
 ('Estrutural','Agregado/Subchassi dianteiro',175),
 ('Estrutural','Agregado/Subchassi traseiro',176),
 ('Direção','Volante',190),
 ('Direção','Coluna de direção',191),
 ('Direção','Eixo intermediário da direção',192),
 ('Direção','Caixa de direção',193),
 ('Direção','Terminal de direção direito',194),
 ('Direção','Terminal de direção esquerdo',195),
 ('Direção','Barra axial direita',196),
 ('Direção','Barra axial esquerda',197),
 ('Direção','Bomba/Motor da direção assistida',198),
 ('Direção','Reservatório da direção hidráulica',199),
 ('Suspensão e rodagem','Amortecedor dianteiro direito',220),
 ('Suspensão e rodagem','Amortecedor dianteiro esquerdo',221),
 ('Suspensão e rodagem','Mola dianteira direita',222),
 ('Suspensão e rodagem','Mola dianteira esquerda',223),
 ('Suspensão e rodagem','Bandeja dianteira direita',224),
 ('Suspensão e rodagem','Bandeja dianteira esquerda',225),
 ('Suspensão e rodagem','Pivô dianteiro direito',226),
 ('Suspensão e rodagem','Pivô dianteiro esquerdo',227),
 ('Suspensão e rodagem','Manga de eixo dianteira direita',228),
 ('Suspensão e rodagem','Manga de eixo dianteira esquerda',229),
 ('Suspensão e rodagem','Rolamento/Cubo dianteiro direito',230),
 ('Suspensão e rodagem','Rolamento/Cubo dianteiro esquerdo',231),
 ('Suspensão e rodagem','Amortecedor traseiro direito',232),
 ('Suspensão e rodagem','Amortecedor traseiro esquerdo',233),
 ('Suspensão e rodagem','Mola traseira direita',234),
 ('Suspensão e rodagem','Mola traseira esquerda',235),
 ('Suspensão e rodagem','Braço de suspensão traseiro direito',236),
 ('Suspensão e rodagem','Braço de suspensão traseiro esquerdo',237),
 ('Suspensão e rodagem','Eixo traseiro/Agregado traseiro',238),
 ('Suspensão e rodagem','Roda dianteira direita',239),
 ('Suspensão e rodagem','Roda dianteira esquerda',240),
 ('Suspensão e rodagem','Roda traseira direita',241),
 ('Suspensão e rodagem','Roda traseira esquerda',242),
 ('Suspensão e rodagem','Pneu dianteiro direito',243),
 ('Suspensão e rodagem','Pneu dianteiro esquerdo',244),
 ('Suspensão e rodagem','Pneu traseiro direito',245),
 ('Suspensão e rodagem','Pneu traseiro esquerdo',246),
 ('Freios e ABS','Disco de freio dianteiro direito',260),
 ('Freios e ABS','Disco de freio dianteiro esquerdo',261),
 ('Freios e ABS','Pinça de freio dianteira direita',262),
 ('Freios e ABS','Pinça de freio dianteira esquerda',263),
 ('Freios e ABS','Conjunto de freio traseiro direito',264),
 ('Freios e ABS','Conjunto de freio traseiro esquerdo',265),
 ('Freios e ABS','Cilindro mestre de freio',266),
 ('Freios e ABS','Hidrovácuo/Servo-freio',267),
 ('Freios e ABS','Módulo ABS/ESC',268),
 ('Freios e ABS','Sensor ABS dianteiro direito',269),
 ('Freios e ABS','Sensor ABS dianteiro esquerdo',270),
 ('Freios e ABS','Sensor ABS traseiro direito',271),
 ('Freios e ABS','Sensor ABS traseiro esquerdo',272),
 ('Freios e ABS','Tubulações/Mangueiras de freio',273),
 ('Freios e ABS','Freio de estacionamento',274),
 ('Motor e alimentação','Motor/Bloco do motor',290),
 ('Motor e alimentação','Cabeçote do motor',291),
 ('Motor e alimentação','Cárter do motor',292),
 ('Motor e alimentação','Coxim do motor direito',293),
 ('Motor e alimentação','Coxim do motor esquerdo',294),
 ('Motor e alimentação','Coxim traseiro do motor/câmbio',295),
 ('Motor e alimentação','Coletor de admissão',296),
 ('Motor e alimentação','Corpo de borboleta',297),
 ('Motor e alimentação','Filtro/Caixa do filtro de ar',298),
 ('Motor e alimentação','Turbocompressor (quando aplicável)',299),
 ('Motor e alimentação','Intercooler (quando aplicável)',300),
 ('Motor e alimentação','Sistema de injeção',301),
 ('Motor e alimentação','Bomba de combustível',302),
 ('Motor e alimentação','Tanque de combustível',303),
 ('Motor e alimentação','Tubulações de combustível',304),
 ('Arrefecimento e climatização','Radiador',320),
 ('Arrefecimento e climatização','Condensador do ar-condicionado',321),
 ('Arrefecimento e climatização','Ventoinha/Eletroventilador',322),
 ('Arrefecimento e climatização','Defletor/Carenagem do radiador',323),
 ('Arrefecimento e climatização','Reservatório de expansão',324),
 ('Arrefecimento e climatização','Mangueiras do arrefecimento',325),
 ('Arrefecimento e climatização','Bomba d’água',326),
 ('Arrefecimento e climatização','Compressor do ar-condicionado',327),
 ('Arrefecimento e climatização','Evaporador do ar-condicionado',328),
 ('Arrefecimento e climatização','Tubulações do ar-condicionado',329),
 ('Transmissão e tração','Câmbio/Transmissão',350),
 ('Transmissão e tração','Conversor de torque (automático)',351),
 ('Transmissão e tração','Embreagem (manual)',352),
 ('Transmissão e tração','Cilindro mestre da embreagem',353),
 ('Transmissão e tração','Semi-eixo dianteiro direito',354),
 ('Transmissão e tração','Semi-eixo dianteiro esquerdo',355),
 ('Transmissão e tração','Junta homocinética direita',356),
 ('Transmissão e tração','Junta homocinética esquerda',357),
 ('Transmissão e tração','Cardã (quando aplicável)',358),
 ('Transmissão e tração','Diferencial (quando aplicável)',359),
 ('Transmissão e tração','Caixa de transferência 4x4 (quando aplicável)',360),
 ('Escapamento e emissões','Coletor de escape',380),
 ('Escapamento e emissões','Catalisador',381),
 ('Escapamento e emissões','Sonda lambda pré-catalisador',382),
 ('Escapamento e emissões','Sonda lambda pós-catalisador',383),
 ('Escapamento e emissões','Silencioso intermediário',384),
 ('Escapamento e emissões','Silencioso traseiro',385),
 ('Escapamento e emissões','Tubulação do escapamento',386),
 ('Elétrica e eletrônica','Bateria 12V',410),
 ('Elétrica e eletrônica','Alternador',411),
 ('Elétrica e eletrônica','Motor de partida',412),
 ('Elétrica e eletrônica','Caixa de fusíveis do cofre',413),
 ('Elétrica e eletrônica','Caixa de fusíveis interna',414),
 ('Elétrica e eletrônica','Chicote elétrico do motor',415),
 ('Elétrica e eletrônica','Chicote elétrico da carroceria',416),
 ('Elétrica e eletrônica','Módulo de injeção/ECU',417),
 ('Elétrica e eletrônica','Módulo de carroceria/BCM',418),
 ('Elétrica e eletrônica','Módulo ABS/ESC eletrônico',419),
 ('Elétrica e eletrônica','Módulo de câmbio/TCM',420),
 ('Elétrica e eletrônica','Painel de instrumentos',421),
 ('Elétrica e eletrônica','Central multimídia',422),
 ('Elétrica e eletrônica','Câmera de ré',423),
 ('Elétrica e eletrônica','Sensores de estacionamento dianteiros',424),
 ('Elétrica e eletrônica','Sensores de estacionamento traseiros',425),
 ('Elétrica e eletrônica','Sensor de chuva/luz',426),
 ('Elétrica e eletrônica','Radar/ADAS dianteiro (quando aplicável)',427),
 ('Elétrica e eletrônica','Câmera ADAS no para-brisa (quando aplicável)',428),
 ('Elétrica e eletrônica','Antena',429),
 ('Segurança passiva','Kit airbag',450),
 ('Segurança passiva','Airbag do motorista',451),
 ('Segurança passiva','Airbag do passageiro',452),
 ('Segurança passiva','Airbag lateral dianteiro direito',453),
 ('Segurança passiva','Airbag lateral dianteiro esquerdo',454),
 ('Segurança passiva','Airbag de cortina direito',455),
 ('Segurança passiva','Airbag de cortina esquerdo',456),
 ('Segurança passiva','Módulo do airbag',457),
 ('Segurança passiva','Sensor de impacto dianteiro direito',458),
 ('Segurança passiva','Sensor de impacto dianteiro esquerdo',459),
 ('Segurança passiva','Cinto dianteiro direito',460),
 ('Segurança passiva','Cinto dianteiro esquerdo',461),
 ('Segurança passiva','Pré-tensionador do cinto dianteiro direito',462),
 ('Segurança passiva','Pré-tensionador do cinto dianteiro esquerdo',463),
 ('Segurança passiva','Cintos traseiros',464),
 ('Segurança passiva','Bancos/Encostos de cabeça',465),
 ('Interior e comandos','Painel/Tabelier',490),
 ('Interior e comandos','Console central',491),
 ('Interior e comandos','Porta-luvas',492),
 ('Interior e comandos','Comando do ar-condicionado',493),
 ('Interior e comandos','Comando de luzes',494),
 ('Interior e comandos','Comando de seta/limpador',495),
 ('Interior e comandos','Pedal do freio',496),
 ('Interior e comandos','Pedal do acelerador',497),
 ('Interior e comandos','Pedal da embreagem (quando aplicável)',498),
 ('Interior e comandos','Banco dianteiro direito',499),
 ('Interior e comandos','Banco dianteiro esquerdo',500),
 ('Interior e comandos','Banco traseiro',501),
 ('Interior e comandos','Forro do teto',502),
 ('Interior e comandos','Forro da porta dianteira direita',503),
 ('Interior e comandos','Forro da porta dianteira esquerda',504),
 ('Interior e comandos','Forro da porta traseira direita',505),
 ('Interior e comandos','Forro da porta traseira esquerda',506),
 ('Interior e comandos','Máquina de vidro dianteira direita',507),
 ('Interior e comandos','Máquina de vidro dianteira esquerda',508),
 ('Interior e comandos','Máquina de vidro traseira direita',509),
 ('Interior e comandos','Máquina de vidro traseira esquerda',510),
 ('Híbrido/Elétrico — quando aplicável','Bateria de alta tensão',540),
 ('Híbrido/Elétrico — quando aplicável','Caixa/proteção da bateria de alta tensão',541),
 ('Híbrido/Elétrico — quando aplicável','Cabos de alta tensão',542),
 ('Híbrido/Elétrico — quando aplicável','Conectores de alta tensão',543),
 ('Híbrido/Elétrico — quando aplicável','Inversor/Conversor',544),
 ('Híbrido/Elétrico — quando aplicável','Motor elétrico de tração',545),
 ('Híbrido/Elétrico — quando aplicável','Carregador embarcado',546),
 ('Híbrido/Elétrico — quando aplicável','Porta de recarga',547),
 ('Híbrido/Elétrico — quando aplicável','Sistema de arrefecimento da bateria HV',548),
 ('Híbrido/Elétrico — quando aplicável','Desconector de serviço da bateria HV',549)
) AS x(section,label,ord)
ON CONFLICT (vehicle_category,label) DO UPDATE
SET section=EXCLUDED.section, sort_order=EXCLUDED.sort_order, active=TRUE, updated_at=NOW();

-- Checklist completo: UTILITY
INSERT INTO nh_event_checklist_template_items(id,vehicle_category,section,label,sort_order,active)
SELECT gen_random_uuid(), 'UTILITY', x.section, x.label, x.ord, TRUE
FROM (VALUES
 ('Dianteira','Para-choque dianteiro',10),
 ('Dianteira','Alma do para-choque dianteiro',11),
 ('Dianteira','Grade frontal',12),
 ('Dianteira','Capô',13),
 ('Dianteira','Fechadura do capô',14),
 ('Dianteira','Farol direito',15),
 ('Dianteira','Farol esquerdo',16),
 ('Dianteira','Farol auxiliar direito',17),
 ('Dianteira','Farol auxiliar esquerdo',18),
 ('Dianteira','Para-lama dianteiro direito',19),
 ('Dianteira','Para-lama dianteiro esquerdo',20),
 ('Dianteira','Painel frontal',21),
 ('Dianteira','Travessa frontal da carroceria',22),
 ('Lateral direita','Retrovisor direito',40),
 ('Lateral direita','Porta dianteira direita',41),
 ('Lateral direita','Porta traseira direita (quando aplicável)',42),
 ('Lateral direita','Porta lateral deslizante direita (van/furgão)',43),
 ('Lateral direita','Caixa de ar direita',44),
 ('Lateral direita','Lateral direita da carroceria',45),
 ('Lateral direita','Estribo direito',46),
 ('Lateral esquerda','Retrovisor esquerdo',60),
 ('Lateral esquerda','Porta dianteira esquerda',61),
 ('Lateral esquerda','Porta traseira esquerda (quando aplicável)',62),
 ('Lateral esquerda','Porta lateral deslizante esquerda (van/furgão)',63),
 ('Lateral esquerda','Caixa de ar esquerda',64),
 ('Lateral esquerda','Lateral esquerda da carroceria',65),
 ('Lateral esquerda','Estribo esquerdo',66),
 ('Traseira e carga','Para-choque traseiro',80),
 ('Traseira e carga','Tampa traseira/Caçamba',81),
 ('Traseira e carga','Porta traseira direita (furgão)',82),
 ('Traseira e carga','Porta traseira esquerda (furgão)',83),
 ('Traseira e carga','Lanterna traseira direita',84),
 ('Traseira e carga','Lanterna traseira esquerda',85),
 ('Traseira e carga','Painel traseiro',86),
 ('Traseira e carga','Assoalho do compartimento de carga',87),
 ('Traseira e carga','Caçamba',88),
 ('Traseira e carga','Protetor de caçamba',89),
 ('Traseira e carga','Santo-antônio (quando aplicável)',90),
 ('Traseira e carga','Capota marítima (quando aplicável)',91),
 ('Traseira e carga','Baú/Implemento leve (quando aplicável)',92),
 ('Traseira e carga','Suporte/Engate de reboque',93),
 ('Teto e vidros','Para-brisa',110),
 ('Teto e vidros','Vidro traseiro',111),
 ('Teto e vidros','Vidro dianteiro direito',112),
 ('Teto e vidros','Vidro dianteiro esquerdo',113),
 ('Teto e vidros','Vidros laterais do compartimento',114),
 ('Teto e vidros','Teto',115),
 ('Teto e vidros','Longarina de teto direita',116),
 ('Teto e vidros','Longarina de teto esquerda',117),
 ('Teto e vidros','Rack de teto',118),
 ('Estrutural','Longarina direita',130),
 ('Estrutural','Longarina esquerda',131),
 ('Estrutural','Travessa dianteira',132),
 ('Estrutural','Travessa central',133),
 ('Estrutural','Travessa traseira',134),
 ('Estrutural','Painel corta-fogo',135),
 ('Estrutural','Assoalho da cabine',136),
 ('Estrutural','Assoalho de carga',137),
 ('Estrutural','Coluna A direita',138),
 ('Estrutural','Coluna A esquerda',139),
 ('Estrutural','Coluna B direita',140),
 ('Estrutural','Coluna B esquerda',141),
 ('Estrutural','Coluna C/D direita',142),
 ('Estrutural','Coluna C/D esquerda',143),
 ('Estrutural','Agregado/Subchassi dianteiro',144),
 ('Estrutural','Agregado/Subchassi traseiro',145),
 ('Direção','Volante',160),
 ('Direção','Coluna de direção',161),
 ('Direção','Caixa de direção',162),
 ('Direção','Terminais e barras de direção',163),
 ('Direção','Bomba/Motor da direção assistida',164),
 ('Suspensão, eixos e rodagem','Suspensão dianteira direita',180),
 ('Suspensão, eixos e rodagem','Suspensão dianteira esquerda',181),
 ('Suspensão, eixos e rodagem','Suspensão traseira direita',182),
 ('Suspensão, eixos e rodagem','Suspensão traseira esquerda',183),
 ('Suspensão, eixos e rodagem','Molas/Feixes de mola traseiros',184),
 ('Suspensão, eixos e rodagem','Amortecedores traseiros',185),
 ('Suspensão, eixos e rodagem','Eixo dianteiro',186),
 ('Suspensão, eixos e rodagem','Eixo traseiro',187),
 ('Suspensão, eixos e rodagem','Rolamentos/Cubos',188),
 ('Suspensão, eixos e rodagem','Roda dianteira direita',189),
 ('Suspensão, eixos e rodagem','Roda dianteira esquerda',190),
 ('Suspensão, eixos e rodagem','Roda traseira direita',191),
 ('Suspensão, eixos e rodagem','Roda traseira esquerda',192),
 ('Suspensão, eixos e rodagem','Pneu dianteiro direito',193),
 ('Suspensão, eixos e rodagem','Pneu dianteiro esquerdo',194),
 ('Suspensão, eixos e rodagem','Pneu traseiro direito',195),
 ('Suspensão, eixos e rodagem','Pneu traseiro esquerdo',196),
 ('Suspensão, eixos e rodagem','Estepe/Suporte do estepe',197),
 ('Freios e estabilidade','Discos/Pinças dianteiros',210),
 ('Freios e estabilidade','Freios traseiros',211),
 ('Freios e estabilidade','Cilindro mestre',212),
 ('Freios e estabilidade','Hidrovácuo/Servo-freio',213),
 ('Freios e estabilidade','Módulo ABS/ESC',214),
 ('Freios e estabilidade','Sensores ABS',215),
 ('Freios e estabilidade','Tubulações/Mangueiras de freio',216),
 ('Freios e estabilidade','Freio de estacionamento',217),
 ('Motor e alimentação','Motor/Bloco',240),
 ('Motor e alimentação','Cabeçote',241),
 ('Motor e alimentação','Cárter',242),
 ('Motor e alimentação','Coxins do motor/câmbio',243),
 ('Motor e alimentação','Admissão/Filtro de ar',244),
 ('Motor e alimentação','Turbocompressor (quando aplicável)',245),
 ('Motor e alimentação','Intercooler (quando aplicável)',246),
 ('Motor e alimentação','Sistema de injeção',247),
 ('Motor e alimentação','Bomba de combustível',248),
 ('Motor e alimentação','Tanque de combustível',249),
 ('Motor e alimentação','Tubulações de combustível',250),
 ('Arrefecimento e climatização','Radiador',270),
 ('Arrefecimento e climatização','Condensador do ar-condicionado',271),
 ('Arrefecimento e climatização','Ventoinha',272),
 ('Arrefecimento e climatização','Reservatório de expansão',273),
 ('Arrefecimento e climatização','Mangueiras do arrefecimento',274),
 ('Arrefecimento e climatização','Bomba d’água',275),
 ('Arrefecimento e climatização','Compressor do ar-condicionado',276),
 ('Arrefecimento e climatização','Evaporador/Tubulações do ar-condicionado',277),
 ('Transmissão e tração','Câmbio/Transmissão',290),
 ('Transmissão e tração','Embreagem (manual)',291),
 ('Transmissão e tração','Conversor de torque (automático)',292),
 ('Transmissão e tração','Semi-eixos dianteiros',293),
 ('Transmissão e tração','Cardã',294),
 ('Transmissão e tração','Cruzetas do cardã',295),
 ('Transmissão e tração','Diferencial dianteiro (4x4 quando aplicável)',296),
 ('Transmissão e tração','Diferencial traseiro',297),
 ('Transmissão e tração','Caixa de transferência 4x4 (quando aplicável)',298),
 ('Transmissão e tração','Cubos de roda livre (quando aplicável)',299),
 ('Escapamento e emissões','Coletor de escape',320),
 ('Escapamento e emissões','Catalisador',321),
 ('Escapamento e emissões','DPF/Filtro de partículas (diesel quando aplicável)',322),
 ('Escapamento e emissões','Sistema SCR/ARLA 32 (diesel quando aplicável)',323),
 ('Escapamento e emissões','Silencioso',324),
 ('Escapamento e emissões','Tubulação de escapamento',325),
 ('Escapamento e emissões','Sensores de emissões',326),
 ('Elétrica e eletrônica','Bateria 12V',350),
 ('Elétrica e eletrônica','Alternador',351),
 ('Elétrica e eletrônica','Motor de partida',352),
 ('Elétrica e eletrônica','Caixas de fusíveis',353),
 ('Elétrica e eletrônica','Chicote do motor',354),
 ('Elétrica e eletrônica','Chicote da carroceria',355),
 ('Elétrica e eletrônica','ECU/Módulo de injeção',356),
 ('Elétrica e eletrônica','BCM/Módulo de carroceria',357),
 ('Elétrica e eletrônica','Módulo eletrônico ABS/ESC',358),
 ('Elétrica e eletrônica','Módulo de câmbio',359),
 ('Elétrica e eletrônica','Painel de instrumentos',360),
 ('Elétrica e eletrônica','Central multimídia',361),
 ('Elétrica e eletrônica','Câmera de ré',362),
 ('Elétrica e eletrônica','Sensores de estacionamento',363),
 ('Elétrica e eletrônica','Radar/Câmera ADAS (quando aplicável)',364),
 ('Elétrica e eletrônica','Iluminação do compartimento de carga',365),
 ('Segurança passiva','Kit airbag',390),
 ('Segurança passiva','Airbag motorista',391),
 ('Segurança passiva','Airbag passageiro',392),
 ('Segurança passiva','Airbags laterais/cortina (quando aplicável)',393),
 ('Segurança passiva','Módulo do airbag',394),
 ('Segurança passiva','Sensores de impacto',395),
 ('Segurança passiva','Cintos dianteiros',396),
 ('Segurança passiva','Pré-tensionadores dos cintos dianteiros',397),
 ('Segurança passiva','Cintos traseiros (quando aplicável)',398),
 ('Interior e comandos','Painel/Tabelier',420),
 ('Interior e comandos','Console central',421),
 ('Interior e comandos','Comandos de climatização',422),
 ('Interior e comandos','Pedal de freio',423),
 ('Interior e comandos','Pedal de acelerador',424),
 ('Interior e comandos','Pedal de embreagem (quando aplicável)',425),
 ('Interior e comandos','Banco motorista',426),
 ('Interior e comandos','Banco passageiro',427),
 ('Interior e comandos','Bancos traseiros (quando aplicável)',428),
 ('Interior e comandos','Forros internos',429),
 ('Interior e comandos','Máquinas de vidro',430),
 ('Interior e comandos','Travas/Fechaduras elétricas',431),
 ('Híbrido/Elétrico — quando aplicável','Bateria de alta tensão',450),
 ('Híbrido/Elétrico — quando aplicável','Proteção da bateria HV',451),
 ('Híbrido/Elétrico — quando aplicável','Cabos de alta tensão',452),
 ('Híbrido/Elétrico — quando aplicável','Inversor/Conversor',453),
 ('Híbrido/Elétrico — quando aplicável','Motor elétrico de tração',454),
 ('Híbrido/Elétrico — quando aplicável','Carregador embarcado',455),
 ('Híbrido/Elétrico — quando aplicável','Porta de recarga',456),
 ('Híbrido/Elétrico — quando aplicável','Sistema de arrefecimento HV',457)
) AS x(section,label,ord)
ON CONFLICT (vehicle_category,label) DO UPDATE
SET section=EXCLUDED.section, sort_order=EXCLUDED.sort_order, active=TRUE, updated_at=NOW();

-- Checklist completo: TRUCK
INSERT INTO nh_event_checklist_template_items(id,vehicle_category,section,label,sort_order,active)
SELECT gen_random_uuid(), 'TRUCK', x.section, x.label, x.ord, TRUE
FROM (VALUES
 ('Cabine — dianteira','Para-choque dianteiro',10),
 ('Cabine — dianteira','Suportes do para-choque',11),
 ('Cabine — dianteira','Grade frontal',12),
 ('Cabine — dianteira','Painel frontal da cabine',13),
 ('Cabine — dianteira','Farol direito',14),
 ('Cabine — dianteira','Farol esquerdo',15),
 ('Cabine — dianteira','Farol auxiliar direito',16),
 ('Cabine — dianteira','Farol auxiliar esquerdo',17),
 ('Cabine — dianteira','Pisca dianteiro direito',18),
 ('Cabine — dianteira','Pisca dianteiro esquerdo',19),
 ('Cabine — dianteira','Para-lama dianteiro direito',20),
 ('Cabine — dianteira','Para-lama dianteiro esquerdo',21),
 ('Cabine — dianteira','Degrau dianteiro/acesso',22),
 ('Cabine — laterais','Retrovisor principal direito',40),
 ('Cabine — laterais','Retrovisor auxiliar direito',41),
 ('Cabine — laterais','Retrovisor principal esquerdo',42),
 ('Cabine — laterais','Retrovisor auxiliar esquerdo',43),
 ('Cabine — laterais','Porta direita',44),
 ('Cabine — laterais','Dobradiças/Fechadura da porta direita',45),
 ('Cabine — laterais','Porta esquerda',46),
 ('Cabine — laterais','Dobradiças/Fechadura da porta esquerda',47),
 ('Cabine — laterais','Estribo direito',48),
 ('Cabine — laterais','Estribo esquerdo',49),
 ('Cabine — laterais','Defletor lateral direito',50),
 ('Cabine — laterais','Defletor lateral esquerdo',51),
 ('Cabine — teto e vidros','Para-brisa',70),
 ('Cabine — teto e vidros','Vidro porta direita',71),
 ('Cabine — teto e vidros','Vidro porta esquerda',72),
 ('Cabine — teto e vidros','Vidro traseiro da cabine',73),
 ('Cabine — teto e vidros','Teto da cabine',74),
 ('Cabine — teto e vidros','Defletor de teto',75),
 ('Cabine — teto e vidros','Palhetas/Braços do limpador',76),
 ('Cabine — teto e vidros','Motor do limpador',77),
 ('Cabine — estrutura e basculamento','Estrutura da cabine',90),
 ('Cabine — estrutura e basculamento','Assoalho da cabine',91),
 ('Cabine — estrutura e basculamento','Painel corta-fogo',92),
 ('Cabine — estrutura e basculamento','Coluna A direita',93),
 ('Cabine — estrutura e basculamento','Coluna A esquerda',94),
 ('Cabine — estrutura e basculamento','Suportes/Coxins da cabine',95),
 ('Cabine — estrutura e basculamento','Mecanismo de basculamento da cabine',96),
 ('Cabine — estrutura e basculamento','Cilindro/Bomba de basculamento',97),
 ('Cabine — estrutura e basculamento','Trava da cabine',98),
 ('Chassi e estrutura pesada','Longarina direita do chassi',120),
 ('Chassi e estrutura pesada','Longarina esquerda do chassi',121),
 ('Chassi e estrutura pesada','Travessa dianteira do chassi',122),
 ('Chassi e estrutura pesada','Travessas centrais do chassi',123),
 ('Chassi e estrutura pesada','Travessa traseira do chassi',124),
 ('Chassi e estrutura pesada','Suportes de carroceria/implemento',125),
 ('Chassi e estrutura pesada','Para-lama traseiro direito',126),
 ('Chassi e estrutura pesada','Para-lama traseiro esquerdo',127),
 ('Chassi e estrutura pesada','Para-choque traseiro',128),
 ('Chassi e estrutura pesada','Protetor lateral direito',129),
 ('Chassi e estrutura pesada','Protetor lateral esquerdo',130),
 ('Chassi e estrutura pesada','Protetor inferior traseiro',131),
 ('Direção','Volante',150),
 ('Direção','Coluna de direção',151),
 ('Direção','Caixa de direção',152),
 ('Direção','Braço Pitman',153),
 ('Direção','Barra de direção longitudinal',154),
 ('Direção','Barra de ligação',155),
 ('Direção','Terminais de direção',156),
 ('Direção','Bomba da direção hidráulica',157),
 ('Direção','Reservatório da direção hidráulica',158),
 ('Direção','Mangueiras da direção',159),
 ('Eixo e suspensão dianteira','Eixo dianteiro',180),
 ('Eixo e suspensão dianteira','Feixe/Molas dianteiras',181),
 ('Eixo e suspensão dianteira','Amortecedor dianteiro direito',182),
 ('Eixo e suspensão dianteira','Amortecedor dianteiro esquerdo',183),
 ('Eixo e suspensão dianteira','Buchas/Pinos da suspensão dianteira',184),
 ('Eixo e suspensão dianteira','Barra estabilizadora dianteira',185),
 ('Eixo e suspensão dianteira','Cubos/Rolamentos dianteiros',186),
 ('Eixos e suspensão traseira','Eixo traseiro motriz',200),
 ('Eixos e suspensão traseira','Segundo eixo traseiro (quando aplicável)',201),
 ('Eixos e suspensão traseira','Terceiro eixo/eixo auxiliar (quando aplicável)',202),
 ('Eixos e suspensão traseira','Feixes de mola traseiros',203),
 ('Eixos e suspensão traseira','Bolsas de ar da suspensão (quando aplicável)',204),
 ('Eixos e suspensão traseira','Amortecedores traseiros',205),
 ('Eixos e suspensão traseira','Barras tensoras/Reação',206),
 ('Eixos e suspensão traseira','Válvula niveladora da suspensão pneumática',207),
 ('Eixos e suspensão traseira','Cubos/Rolamentos traseiros',208),
 ('Rodas e pneus','Rodas dianteiras',230),
 ('Rodas e pneus','Pneus dianteiros',231),
 ('Rodas e pneus','Rodas traseiras eixo motriz',232),
 ('Rodas e pneus','Pneus traseiros eixo motriz',233),
 ('Rodas e pneus','Rodas/pneus do eixo auxiliar (quando aplicável)',234),
 ('Rodas e pneus','Estepe',235),
 ('Rodas e pneus','Suporte do estepe',236),
 ('Freios pneumáticos/ABS','Compressor de ar',250),
 ('Freios pneumáticos/ABS','Secador de ar',251),
 ('Freios pneumáticos/ABS','Reservatórios de ar',252),
 ('Freios pneumáticos/ABS','Válvula de proteção multicircuito',253),
 ('Freios pneumáticos/ABS','Válvula pedal do freio',254),
 ('Freios pneumáticos/ABS','Cuícas/Câmaras de freio dianteiras',255),
 ('Freios pneumáticos/ABS','Cuícas/Câmaras de freio traseiras',256),
 ('Freios pneumáticos/ABS','Tubulações/Mangueiras pneumáticas',257),
 ('Freios pneumáticos/ABS','Discos/Tambores de freio dianteiros',258),
 ('Freios pneumáticos/ABS','Discos/Tambores de freio traseiros',259),
 ('Freios pneumáticos/ABS','Pinças/Sapatas de freio',260),
 ('Freios pneumáticos/ABS','Módulo ABS/EBS',261),
 ('Freios pneumáticos/ABS','Sensores ABS das rodas',262),
 ('Freios pneumáticos/ABS','Freio de estacionamento',263),
 ('Freios pneumáticos/ABS','Freio motor/Retarder (quando aplicável)',264),
 ('Motor','Motor/Bloco',290),
 ('Motor','Cabeçote',291),
 ('Motor','Cárter',292),
 ('Motor','Coxins/Suportes do motor',293),
 ('Motor','Tampa de válvulas',294),
 ('Motor','Sistema de admissão',295),
 ('Motor','Filtro/Caixa de ar',296),
 ('Motor','Turbocompressor',297),
 ('Motor','Intercooler',298),
 ('Motor','Sistema de injeção diesel/Common rail',299),
 ('Motor','Bomba de alta pressão',300),
 ('Motor','Bicos injetores',301),
 ('Arrefecimento','Radiador',320),
 ('Arrefecimento','Intercooler — estrutura/tubulações',321),
 ('Arrefecimento','Ventoinha/Hélice',322),
 ('Arrefecimento','Embreagem viscosa da ventoinha',323),
 ('Arrefecimento','Defletor do radiador',324),
 ('Arrefecimento','Reservatório de expansão',325),
 ('Arrefecimento','Mangueiras do arrefecimento',326),
 ('Arrefecimento','Bomba d’água',327),
 ('Transmissão e trem de força','Câmbio/Transmissão',350),
 ('Transmissão e trem de força','Embreagem',351),
 ('Transmissão e trem de força','Servo/Cilindro da embreagem',352),
 ('Transmissão e trem de força','Seletor/Trambulador',353),
 ('Transmissão e trem de força','Cardã dianteiro',354),
 ('Transmissão e trem de força','Cardã traseiro',355),
 ('Transmissão e trem de força','Cruzetas',356),
 ('Transmissão e trem de força','Suporte/Rolamento do cardã',357),
 ('Transmissão e trem de força','Diferencial eixo motriz',358),
 ('Transmissão e trem de força','Diferencial segundo eixo (quando aplicável)',359),
 ('Transmissão e trem de força','Redutores de cubo (quando aplicável)',360),
 ('Combustível e emissões','Tanque de combustível direito',380),
 ('Combustível e emissões','Tanque de combustível esquerdo (quando aplicável)',381),
 ('Combustível e emissões','Cintas/Suportes do tanque',382),
 ('Combustível e emissões','Tubulações de combustível',383),
 ('Combustível e emissões','Filtro de combustível',384),
 ('Combustível e emissões','Catalisador/Unidade de pós-tratamento',385),
 ('Combustível e emissões','DPF/Filtro de partículas',386),
 ('Combustível e emissões','Sistema SCR/ARLA 32',387),
 ('Combustível e emissões','Tanque de ARLA 32',388),
 ('Combustível e emissões','Bomba/Módulo de ARLA',389),
 ('Combustível e emissões','Sensores NOx/Temperatura',390),
 ('Combustível e emissões','Silencioso/Escapamento',391),
 ('Elétrica e eletrônica','Baterias 12/24V',420),
 ('Elétrica e eletrônica','Caixa/Suporte das baterias',421),
 ('Elétrica e eletrônica','Alternador',422),
 ('Elétrica e eletrônica','Motor de partida',423),
 ('Elétrica e eletrônica','Chave geral',424),
 ('Elétrica e eletrônica','Caixas de fusíveis/Relés',425),
 ('Elétrica e eletrônica','Chicote do motor',426),
 ('Elétrica e eletrônica','Chicote do chassi',427),
 ('Elétrica e eletrônica','ECU do motor',428),
 ('Elétrica e eletrônica','TCU/Módulo do câmbio',429),
 ('Elétrica e eletrônica','Módulo eletrônico ABS/EBS',430),
 ('Elétrica e eletrônica','Módulo de carroceria/cabine',431),
 ('Elétrica e eletrônica','Painel de instrumentos',432),
 ('Elétrica e eletrônica','Tacógrafo',433),
 ('Elétrica e eletrônica','Central multimídia/Rádio',434),
 ('Elétrica e eletrônica','Câmera de ré',435),
 ('Elétrica e eletrônica','Sensores/Radares ADAS (quando aplicável)',436),
 ('Elétrica e eletrônica','Lanterna traseira direita',437),
 ('Elétrica e eletrônica','Lanterna traseira esquerda',438),
 ('Elétrica e eletrônica','Luzes laterais/Delimitadoras',439),
 ('Elétrica e eletrônica','Tomada elétrica do implemento/reboque',440),
 ('Segurança e interior da cabine','Airbag motorista (quando equipado)',460),
 ('Segurança e interior da cabine','Airbag passageiro (quando equipado)',461),
 ('Segurança e interior da cabine','Módulo airbag (quando equipado)',462),
 ('Segurança e interior da cabine','Cinto motorista',463),
 ('Segurança e interior da cabine','Cinto passageiro',464),
 ('Segurança e interior da cabine','Banco motorista',465),
 ('Segurança e interior da cabine','Banco passageiro',466),
 ('Segurança e interior da cabine','Painel/Tabelier',467),
 ('Segurança e interior da cabine','Console central',468),
 ('Segurança e interior da cabine','Pedal de freio',469),
 ('Segurança e interior da cabine','Pedal de acelerador',470),
 ('Segurança e interior da cabine','Pedal de embreagem (quando aplicável)',471),
 ('Segurança e interior da cabine','Climatização/Ar-condicionado',472),
 ('Segurança e interior da cabine','Sistema de travamento da cabine',473),
 ('Acoplamento e implemento','Quinta roda (cavalo mecânico)',500),
 ('Acoplamento e implemento','Mesa/Placa da quinta roda',501),
 ('Acoplamento e implemento','Pino rei do implemento',502),
 ('Acoplamento e implemento','Mangueiras pneumáticas do reboque',503),
 ('Acoplamento e implemento','Cabos/tomadas elétricas do reboque',504),
 ('Acoplamento e implemento','Engate traseiro/Pino de reboque',505),
 ('Acoplamento e implemento','Carroceria/Caçamba/Baú',506),
 ('Acoplamento e implemento','Estrutura do implemento',507),
 ('Acoplamento e implemento','Laterais do implemento',508),
 ('Acoplamento e implemento','Teto do baú (quando aplicável)',509),
 ('Acoplamento e implemento','Portas/Tampa traseira do implemento',510),
 ('Acoplamento e implemento','Sistema hidráulico da caçamba (quando aplicável)',511),
 ('Acoplamento e implemento','Cilindro hidráulico do implemento (quando aplicável)',512),
 ('Acoplamento e implemento','Bomba/Tomada de força PTO (quando aplicável)',513),
 ('Acoplamento e implemento','Para-lamas do implemento',514),
 ('Acoplamento e implemento','Lanternas do implemento',515)
) AS x(section,label,ord)
ON CONFLICT (vehicle_category,label) DO UPDATE
SET section=EXCLUDED.section, sort_order=EXCLUDED.sort_order, active=TRUE, updated_at=NOW();

COMMENT ON COLUMN nh_event_records.vehicle_subtype IS 'Subtipo/configuração operacional usado para detalhar o veículo sem misturar categorias de checklist.';
COMMENT ON TABLE nh_event_checklist_template_items IS 'Templates técnicos da oficina separados por categoria de veículo; somente itens ativos são materializados no checklist.';
