const TOKEN_KEY='nhPortalToken',ROLE_KEY='nhPortalRole',LAST_ACTIVITY_KEY='nhPortalLastActivityAt';
const $=id=>document.getElementById(id),qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const state={me:null,events:[],bucket:'NOT_FILLED',current:null,editing:new Set()};
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=v=>v?new Date(v).toLocaleString('pt-BR'):'—';const money=v=>v==null?'':Number(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const token=()=>localStorage.getItem(TOKEN_KEY);function apiUrl(p){return window.NH_API?.backend(p)||p;}function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.className=t?`message ${type}`:'';e.textContent=t;}function toast(t,type='success'){qs('.buyer-toast')?.remove();const e=document.createElement('div');e.className=`buyer-toast message ${type}`;e.textContent=t;Object.assign(e.style,{position:'fixed',right:'16px',bottom:'16px',zIndex:9999,maxWidth:'420px'});document.body.appendChild(e);setTimeout(()=>e.remove(),3800);}function redirectRole(r){if(window.NH_ROUTING?.redirectForRole)return window.NH_ROUTING.redirectForRole(r);location.replace('/');}
async function api(path,opt={}){const headers=new Headers(opt.headers||{});if(token())headers.set('Authorization',`Bearer ${token()}`);const o={...opt,headers,cache:'no-store'};if(o.body&&typeof o.body!=='string'&&!(o.body instanceof FormData)){headers.set('Content-Type','application/json');o.body=JSON.stringify(o.body);}const r=await fetch(apiUrl(path),o);const ct=r.headers.get('content-type')||'';const b=ct.includes('application/json')?await r.json().catch(()=>null):await r.text().catch(()=>'');if(!r.ok){if(r.status===401){showLogin('Sua sessão expirou. Entre novamente.');}throw new Error(b?.message||b?.error||`Não foi possível concluir (${r.status}).`);}return b;}
function showLogin(text=''){state.me=null;$('login-view').hidden=false;$('app-view').hidden=true;$('logout').hidden=true;msg('login-message',text);}function showApp(){$('login-view').hidden=true;$('app-view').hidden=false;$('logout').hidden=false;}
async function login(e){e.preventDefault();msg('login-message');const b=qs('#login-form button');b.disabled=true;try{const r=await fetch(apiUrl('/api/auth/login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.message||'Usuário ou senha inválidos.');localStorage.setItem(TOKEN_KEY,body.token);localStorage.setItem(ROLE_KEY,body.role);localStorage.setItem(LAST_ACTIVITY_KEY,String(Date.now()));if(body.role!=='BUYER'){redirectRole(body.role);return;}await bootAuthenticated();}catch(err){msg('login-message',err.message);}finally{b.disabled=false;}}
async function bootAuthenticated(){state.me=await api('/api/auth/me');if(state.me.role!=='BUYER'){redirectRole(state.me.role);return;}showApp();$('user-chip').textContent=`✓ ${state.me.displayName||state.me.username}`;await loadAll();route();}
async function boot(){if(!token())return showLogin();try{await bootAuthenticated();}catch(e){showLogin(e.message);}}
async function loadAll(){msg('queue-message');const q=$('search')?.value.trim()||'';try{state.events=await api(`/api/procurement/events${q?`?q=${encodeURIComponent(q)}`:''}`);renderQueue();}catch(e){msg('queue-message',e.message);}}
function bucketLabel(b){return b==='NOT_FILLED'?'Não preenchido':b==='REQUESTED'?'Solicitado':'Finalizado';}
function renderQueue(){const groups={NOT_FILLED:[],REQUESTED:[],FINALIZED:[]};state.events.forEach(e=>(groups[e.bucket]||groups.NOT_FILLED).push(e));$('kpi-not-filled').textContent=groups.NOT_FILLED.length;$('kpi-requested').textContent=groups.REQUESTED.length;$('kpi-finalized').textContent=groups.FINALIZED.length;$('kpi-total').textContent=state.events.length;$('count-not-filled').textContent=groups.NOT_FILLED.length;$('count-requested').textContent=groups.REQUESTED.length;$('count-finalized').textContent=groups.FINALIZED.length;qsa('[data-bucket]').forEach(b=>b.classList.toggle('active',b.dataset.bucket===state.bucket));const list=groups[state.bucket]||[];const root=$('event-list');if(!list.length){root.innerHTML='<div class="card empty-buyer">Nenhum evento nesta situação.</div>';return;}root.innerHTML=list.map(e=>`<article class="buyer-card"><span class="eyebrow">${h(e.protocol)}</span><h3>${h(e.vehiclePlate)} · ${h(e.vehicleModel)}</h3><p>${h(e.associateName)} · Associado ${h(e.associateNumber)}</p><div class="buyer-card-stats"><span>${e.totalItems} item(ns)</span><span>${e.unfilledItems} não preenchido(s)</span><span>${e.requestedItems} solicitado(s)</span><span>${e.finalizedItems} finalizado(s)</span></div><small>Checklist da oficina concluído em ${h(dt(e.workshopCompletedAt))}</small><div class="actions"><button class="primary open-event" data-id="${e.id}" type="button">Abrir Compras do Evento</button></div></article>`).join('');qsa('.open-event',root).forEach(b=>b.onclick=()=>location.hash=`#/event/${b.dataset.id}`);}
async function openEvent(id){$('queue-view').hidden=true;$('detail-view').hidden=false;$('event-detail').innerHTML='<div class="card">Carregando...</div>';try{state.current=await api(`/api/procurement/events/${id}`);state.editing.clear();renderDetail();}catch(e){$('event-detail').innerHTML=`<div class="message error">${h(e.message)}</div>`;}}
function summary(label,value){return `<div><span>${h(label)}</span><strong>${h(value||'—')}</strong></div>`;}
function renderDetail(){const e=state.current;$('detail-status').textContent=bucketLabel(e.bucket);$('event-detail').innerHTML=`<div class="card buyer-detail-head"><span class="eyebrow">${h(e.protocol)}</span><h2>${h(e.vehiclePlate)} · ${h(e.vehicleBrand||'')} ${h(e.vehicleModel)}</h2><div class="buyer-summary">${summary('Associado',e.associateName)}${summary('Número',e.associateNumber)}${summary('Plano',e.planName)}${summary('Categoria',e.vehicleCategory)}${summary('Oficina concluída por',e.workshopCompletedBy)}${summary('Conclusão da oficina',dt(e.workshopCompletedAt))}</div></div><div class="purchase-list">${e.purchases.map(p=>purchaseHtml(p)).join('')}</div>`;bindPurchases();}
function purchaseHtml(p){const saved=!!p.detailsSavedAt,editing=!saved||state.editing.has(p.id),locked=editing?'':' disabled';return `<article class="purchase-editor ${saved?'saved':''}" data-purchase="${p.id}"><h4>${h(p.itemLabel)}</h4><div class="purchase-grid"><label>Fornecedor<input class="supplier" value="${h(p.supplier||'')}" maxlength="180"${locked}></label><label>Valor (R$)<input class="amount" inputmode="decimal" value="${h(money(p.amount))}"${locked}></label><label>Prazo de entrega<input class="deadline" type="date" value="${h(p.deliveryDeadline||'')}"${locked}></label><label>Status<select class="status"${locked}>${saved?`<option value="REQUESTED" ${p.status==='REQUESTED'?'selected':''}>Solicitado</option><option value="FINALIZED" ${p.status==='FINALIZED'?'selected':''}>Finalizado</option>`:'<option value="REQUESTED" selected>Solicitado</option>'}</select></label><label class="full">Observação<input class="notes" value="${h(p.notes||'')}" maxlength="3000" placeholder="Observação interna"${locked}></label></div><div class="purchase-state-note">${saved?`✓ Registrado no dossiê interno em ${h(dt(p.detailsSavedAt))}${p.detailsSavedBy?` por ${h(p.detailsSavedBy)}`:''}`:'Pendente de preenchimento pelo comprador.'}</div><div class="purchase-actions">${editing?`<button class="secondary save-item" type="button">${saved?'Salvar alterações':'Salvar item'}</button>`:`<button class="outline edit-item" type="button">Editar item</button>`}</div></article>`;}
function parseAmount(v){const s=String(v||'').trim().replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null;}
function bindPurchases(){qsa('.edit-item').forEach(b=>b.onclick=()=>{const row=b.closest('[data-purchase]');state.editing.add(row.dataset.purchase);renderDetail();});qsa('.save-item').forEach(b=>b.onclick=()=>saveItem(b.closest('[data-purchase]')));}
async function saveItem(row){const b=qs('.save-item',row);b.disabled=true;try{const amount=parseAmount(qs('.amount',row).value);state.current=await api(`/api/procurement/events/${state.current.id}/purchases/${row.dataset.purchase}`,{method:'PATCH',body:{supplier:qs('.supplier',row).value.trim(),amount,deliveryDeadline:qs('.deadline',row).value||null,status:qs('.status',row).value,notes:qs('.notes',row).value.trim()}});state.editing.delete(row.dataset.purchase);toast('Compra salva e registrada no dossiê interno.');renderDetail();await loadAll();}catch(e){toast(e.message,'error');}finally{if(document.body.contains(b))b.disabled=false;}}
function route(){const m=location.hash.match(/^#\/event\/([0-9a-f-]+)$/i);if(m)openEvent(m[1]);else{$('detail-view').hidden=true;$('queue-view').hidden=false;state.current=null;}}
$('login-form').addEventListener('submit',login);$('logout').addEventListener('click',()=>{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(ROLE_KEY);showLogin();});$('refresh').addEventListener('click',loadAll);$('search-button').addEventListener('click',loadAll);$('search').addEventListener('keydown',e=>{if(e.key==='Enter')loadAll();});qsa('[data-bucket]').forEach(b=>b.onclick=()=>{state.bucket=b.dataset.bucket;renderQueue();});$('back').addEventListener('click',()=>{location.hash='';});window.addEventListener('hashchange',route);boot();
