const $=id=>document.getElementById(id);const token=new URLSearchParams(location.search).get('token')||'';let current=null;
const api=p=>window.NH_API?.backend(p)||p;const enc=v=>encodeURIComponent(v);
function b64ToBytes(value){const n=String(value||'').replace(/-/g,'+').replace(/_/g,'/'),p=n+'='.repeat((4-n.length%4)%4),bin=atob(p);return Uint8Array.from(bin,c=>c.charCodeAt(0));}
function bytesToB64(value){const b=value instanceof ArrayBuffer?new Uint8Array(value):new Uint8Array(value?.buffer||value||[]);let bin='';for(const x of b)bin+=String.fromCharCode(x);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
function isIOS(){const ua=navigator.userAgent||'';return /iPad|iPhone|iPod/i.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function embeddedIOS(){if(!isIOS())return false;const ua=navigator.userAgent||'';return !(/Safari/i.test(ua)&&!/CriOS|FxiOS|EdgiOS|OPiOS|GSA|FBAN|FBAV|Instagram|WhatsApp/i.test(ua));}
async function geo(){if(!navigator.geolocation)return{};return new Promise(r=>{const t=setTimeout(()=>r({}),5000);navigator.geolocation.getCurrentPosition(p=>{clearTimeout(t);r({latitude:Number(p.coords.latitude),longitude:Number(p.coords.longitude),accuracyMeters:Number(p.coords.accuracy)})},()=>{clearTimeout(t);r({})},{timeout:4500,maximumAge:60000})})}
async function device(){let platformAuthenticatorAvailable=false;try{platformAuthenticatorAvailable=Boolean(await PublicKeyCredential?.isUserVerifyingPlatformAuthenticatorAvailable?.())}catch(_){}const g=await geo();return{userAgent:navigator.userAgent||'',platform:navigator.userAgentData?.platform||navigator.platform||'',vendor:navigator.vendor||'',language:navigator.language||'',languages:Array.isArray(navigator.languages)?navigator.languages.join(','):'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'',screenWidth:Number(screen?.width||0),screenHeight:Number(screen?.height||0),colorDepth:Number(screen?.colorDepth||0),pixelRatio:Number(devicePixelRatio||1),touchPoints:Number(navigator.maxTouchPoints||0),hardwareConcurrency:Number(navigator.hardwareConcurrency||0),deviceMemory:navigator.deviceMemory==null?null:Number(navigator.deviceMemory),cookieEnabled:Boolean(navigator.cookieEnabled),online:Boolean(navigator.onLine),webdriver:Boolean(navigator.webdriver),webauthnAvailable:Boolean(window.PublicKeyCredential&&navigator.credentials),platformAuthenticatorAvailable,currentUrl:location.href,referrer:document.referrer||'',latitude:g.latitude??null,longitude:g.longitude??null,accuracyMeters:g.accuracyMeters??null,capturedAt:new Date().toISOString()}}
async function post(path,body){const r=await fetch(api(`/api/public/events/acceptance/${enc(token)}${path}`),{method:'POST',headers:body==null?{}:{'Content-Type':'application/json'},body:body==null?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||d?.error||'Não foi possível concluir o aceite digital.');return d}
function render(d){current=d;$('loading').hidden=true;$('accept-card').hidden=false;$('protocol').textContent=d.protocol||'—';$('associate').textContent=d.associateName||'—';$('vehicle').textContent=`${d.vehiclePlate||'—'} · ${d.vehicleModel||'—'}`;$('accept-status').textContent=d.accepted?'Aceite confirmado':d.eligible?'Aguardando aceite':'Ainda não liberado';const btn=$('confirm-acceptance');btn.hidden=!!d.accepted||!d.eligible;if(d.accepted){$('accept-proof').hidden=false;$('accept-proof').innerHTML=`<strong>✓ Aceite WebAuthn confirmado</strong><br>Data: ${d.acceptedAt?new Date(d.acceptedAt).toLocaleString('pt-BR'):'confirmada'}<br>Verificação do usuário: ${d.userVerified?'confirmada pelo aparelho':'registrada'}<br>Hash da prova: <code>${d.proofHash||'registrado'}</code>`;$('accept-message').textContent='Este dossiê já foi confirmado digitalmente.'}}
async function assertion(options){$('accept-message').textContent='Confirme no aparelho com biometria, Face ID, Touch ID, PIN ou código de bloqueio...';const a=await navigator.credentials.get({publicKey:{challenge:b64ToBytes(options.challenge),rpId:options.rpId,allowCredentials:[{type:'public-key',id:b64ToBytes(options.credentialId)}],userVerification:'required',timeout:Number(options.timeoutMs||120000)}});if(!a)throw new Error('O aparelho não confirmou a assinatura WebAuthn.');return post('/assertion-finish',{id:a.id,rawId:bytesToB64(a.rawId),type:a.type,clientDataJSON:bytesToB64(a.response.clientDataJSON),authenticatorData:bytesToB64(a.response.authenticatorData),signature:bytesToB64(a.response.signature),userHandle:a.response.userHandle?bytesToB64(a.response.userHandle):null})}
async function existing(){try{return await post('/assertion-options',null)}catch(e){if(/Primeiro confirme|credencial segura/i.test(e.message))return null;throw e}}
async function accept(){const btn=$('confirm-acceptance');if(!window.PublicKeyCredential||!navigator.credentials)throw new Error('Este navegador não oferece WebAuthn. Abra o link no Safari, Chrome ou Edge do aparelho.');if(embeddedIOS()){$('ios-help').hidden=false;throw new Error('No iPhone, abra este link diretamente no Safari para continuar.')}btn.disabled=true;try{const meta=await device();let opts=await existing();if(!opts){const reg=await post('/registration-options',meta);$('accept-message').textContent='Crie a chave segura usando a biometria/PIN do aparelho...';const selection={residentKey:isIOS()?'preferred':'discouraged',requireResidentKey:false,userVerification:'required'};if(!isIOS())selection.authenticatorAttachment='platform';const created=await navigator.credentials.create({publicKey:{challenge:b64ToBytes(reg.challenge),rp:{id:reg.rpId,name:reg.rpName},user:{id:b64ToBytes(reg.userId),name:reg.userName,displayName:reg.userDisplayName},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:selection,timeout:Number(reg.timeoutMs||120000),attestation:'none'}});if(!created)throw new Error('O aparelho não criou a credencial segura.');opts=await post('/registration-finish',{id:created.id,rawId:bytesToB64(created.rawId),type:created.type,clientDataJSON:bytesToB64(created.response.clientDataJSON),attestationObject:bytesToB64(created.response.attestationObject),device:meta})}render(await assertion(opts));$('accept-message').textContent='Aceite digital confirmado com sucesso.'}finally{btn.disabled=false}}
$('download-dossier').onclick=()=>{if(!token)return;location.href=api(`/api/public/events/acceptance/${enc(token)}/dossier.pdf`)};$('confirm-acceptance').onclick=()=>accept().catch(e=>{$('accept-message').textContent=e.message||'Não foi possível concluir o aceite.'});
(async()=>{if(!token){$('loading').innerHTML='<p>Link de aceite inválido. Solicite um novo link à Novo Horizonte.</p>';return}try{const r=await fetch(api(`/api/public/events/acceptance/${enc(token)}`),{cache:'no-store'}),d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Link de aceite inválido.');render(d)}catch(e){$('loading').innerHTML=`<p>${String(e.message||e)}</p>`}})();
