const TOKEN_KEY='nhPortalToken',ROLE_KEY='nhPortalRole',CONSULTANT_KEY='nhSelectedConsultant';
const $=id=>document.getElementById(id);let consultants=[];
function token(){return localStorage.getItem(TOKEN_KEY)}
async function api(path,options={}){const h=new Headers(options.headers||{});if(token())h.set('Authorization',`Bearer ${token()}`);const r=await fetch(path,{...options,headers:h});if(!r.ok){const b=await r.json().catch(()=>null);if(r.status===401)logout();throw new Error(b?.message||'Não foi possível concluir a solicitação.')}return r.status===204?null:r.json()}
function message(text,type='error'){const el=$('portal-message');el.className=`message ${type}`;el.textContent=text}
function clearMessage(){const el=$('portal-message');el.className='';el.textContent=''}
function logout(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(ROLE_KEY);localStorage.removeItem(CONSULTANT_KEY);location.reload()}
async function boot(){if(!token())return;$('login-view').hidden=true;$('portal-view').hidden=false;$('logout').hidden=false;try{const me=await api('/api/auth/me');localStorage.setItem(ROLE_KEY,me.role);$('admin-card-wrap').hidden=me.role!=='ADMIN';await loadConsultants();restoreConsultant();}catch(e){message(e.message)}}
async function loadConsultants(){consultants=await api('/api/consultants');$('consultants-list').innerHTML=consultants.map(c=>`<option value="${escapeHtml(c.name)}"></option>`).join('')}
function restoreConsultant(){const c=JSON.parse(localStorage.getItem(CONSULTANT_KEY)||'null');if(c?.id){$('consultant-search').value=c.name;applyConsultant(c)}else{$('tools').hidden=true}}
function applyConsultant(c){localStorage.setItem(CONSULTANT_KEY,JSON.stringify(c));$('current-chip').textContent=`✓ ${c.name}`;$('current-chip').hidden=false;$('tools').hidden=false;$('change-consultant').hidden=false;$('select-consultant').hidden=true;$('show-create').hidden=true;$('consultant-search').disabled=true;clearMessage()}
function changeConsultant(){$('consultant-search').disabled=false;$('consultant-search').value='';$('current-chip').hidden=true;$('tools').hidden=true;$('change-consultant').hidden=true;$('select-consultant').hidden=false;$('show-create').hidden=false;localStorage.removeItem(CONSULTANT_KEY)}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const box=$('login-message');box.textContent='';try{const data=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});localStorage.setItem(TOKEN_KEY,data.token);localStorage.setItem(ROLE_KEY,data.role);location.reload()}catch(err){box.className='message error';box.textContent=err.message}});
$('select-consultant').addEventListener('click',()=>{const value=$('consultant-search').value.trim().toLowerCase();const found=consultants.find(c=>c.name.toLowerCase()===value);if(!found)return message('Selecione um nome da lista ou cadastre um novo consultor.');applyConsultant(found)});
$('show-create').addEventListener('click',()=>{$('create-box').hidden=false;$('new-consultant-name').value=$('consultant-search').value;$('new-consultant-name').focus()});$('cancel-create').addEventListener('click',()=>{$('create-box').hidden=true});
$('create-consultant').addEventListener('click',async()=>{clearMessage();try{const c=await api('/api/consultants',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('new-consultant-name').value.trim()})});await loadConsultants();$('create-box').hidden=true;$('consultant-search').value=c.name;applyConsultant(c);message('Novo consultor cadastrado e selecionado. Ele já aparecerá no painel administrativo.','success')}catch(e){message(e.message)}});
$('change-consultant').addEventListener('click',changeConsultant);$('logout').addEventListener('click',logout);const defaultSgaUrl='https://sga.hinova.com.br/sga/sgav4_novohorizonte/v5/login.php';const configuredSgaUrl=window.NH_CONFIG?.sgaUrl;$('sga-card').href=configuredSgaUrl&&configuredSgaUrl!=='#'?configuredSgaUrl:defaultSgaUrl;boot();
