const TOKEN_KEY='nhPortalToken',ROLE_KEY='nhPortalRole',CONSULTANT_KEY='nhSelectedConsultant';
const $=id=>document.getElementById(id);let consultants=[];let selectedConsultant=null;let dashboardData=null;let dashboardTimer=null;let activeCompletionCommunication=null;const dismissedCompletionIds=new Set();
const QUOTE_STATUS={CREATED:['Pendente','warn'],UNDER_REVIEW:['Em análise','warn'],ACCEPTED:['Aceita','ok'],DECLINED:['Recusada','off'],CANCELLED:['Cancelada','off']};
const INSPECTION_STATUS={CREATED:['Pendente','warn'],UNDER_REVIEW:['Em análise','warn'],COMPLETED:['Aguardando análise','warn'],APPROVED:['Aprovada','ok'],REJECTED:['Recusada','off'],CANCELLED:['Cancelada','off'],EXPIRED:['Expirada','off']};
function token(){return localStorage.getItem(TOKEN_KEY)}
async function api(path,options={}){const h=new Headers(options.headers||{});if(token())h.set('Authorization',`Bearer ${token()}`);const r=await fetch(window.NH_API?.backend(path)||path,{...options,headers:h});if(!r.ok){const b=await r.json().catch(()=>null);if(r.status===401)logout();throw new Error(b?.message||'Não foi possível concluir a solicitação.')}return r.status===204?null:r.json()}
function message(text,type='error'){const el=$('portal-message');el.className=`message ${type}`;el.textContent=text}
function clearMessage(){const el=$('portal-message');el.className='';el.textContent=''}
function logout(){stopDashboardPolling();localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(ROLE_KEY);localStorage.removeItem(CONSULTANT_KEY);location.reload()}
async function boot(){if(!token())return;$('login-view').hidden=true;$('portal-view').hidden=false;$('logout').hidden=false;try{const me=await api('/api/auth/me');localStorage.setItem(ROLE_KEY,me.role);if(me.role==='ADMIN'){location.replace('/admin/');return;}if(me.role==='ANALYST'){location.replace('/analise/');return;}$('admin-card-wrap').hidden=true;await loadConsultants();restoreConsultant();}catch(e){message(e.message)}}
async function loadConsultants(){consultants=await api('/api/consultants');$('consultants-list').innerHTML=consultants.map(c=>`<option value="${escapeHtml(c.name)}"></option>`).join('')}
function restoreConsultant(){const c=JSON.parse(localStorage.getItem(CONSULTANT_KEY)||'null');if(c?.id){$('consultant-search').value=c.name;applyConsultant(c)}else{$('tools').hidden=true;$('activity-dashboard').hidden=true}}
function applyConsultant(c){selectedConsultant=c;localStorage.setItem(CONSULTANT_KEY,JSON.stringify(c));$('current-chip').textContent=`✓ ${c.name}`;$('current-chip').hidden=false;$('tools').hidden=false;$('activity-dashboard').hidden=false;$('change-consultant').hidden=false;$('select-consultant').hidden=true;$('show-create').hidden=true;$('consultant-search').disabled=true;clearMessage();startDashboardPolling();loadDashboard(c).catch(error=>message(error.message))}
function changeConsultant(){stopDashboardPolling();$('consultant-search').disabled=false;$('consultant-search').value='';$('current-chip').hidden=true;$('tools').hidden=true;$('activity-dashboard').hidden=true;$('change-consultant').hidden=true;$('select-consultant').hidden=false;$('show-create').hidden=false;selectedConsultant=null;localStorage.removeItem(CONSULTANT_KEY)}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function date(value){return value?new Date(value).toLocaleString('pt-BR'):'—'}
function badge(status,labels){const [label,kind]=labels[status]||[status||'Não iniciada',''];return `<span class="badge ${kind}">${escapeHtml(label)}</span>`}
function plate(value,zeroKm=false){return value|| (zeroKm?'0 km — sem placa':'—')}
function empty(columns,text){return `<tr><td colspan="${columns}" class="empty-state">${escapeHtml(text)}</td></tr>`}
async function loadDashboard(consultant=selectedConsultant,{silent=false}={}){if(!consultant?.id)return;const button=$('refresh-dashboard');if(!silent){button.disabled=true;button.textContent='Atualizando...'}try{const data=await api(`/api/consultant-dashboard/${encodeURIComponent(consultant.id)}`);dashboardData=data;renderDashboard(data);showNextCompletionCommunication()}finally{if(!silent){button.disabled=false;button.textContent='Atualizar informações'}}}
function renderDashboard(data){$('consultant-quotes-body').innerHTML=(data.quotes||[]).map(item=>`<tr>
<td><strong>${escapeHtml(item.quoteNumber)}</strong></td><td>${escapeHtml(item.customerName)}</td><td>${escapeHtml(plate(item.plate,item.zeroKm))}<small class="table-code">${escapeHtml(item.model||'')}</small></td>
<td>${date(item.createdAt)}</td><td>${date(item.validUntil)}</td><td>${item.expired?'<span class="badge off">Expirada</span>':badge(item.status,QUOTE_STATUS)}</td><td>${badge(item.inspectionStatus,INSPECTION_STATUS)}</td>
</tr>`).join('')||empty(7,'Nenhuma cotação encontrada para este consultor.');
$('consultant-inspections-body').innerHTML=(data.inspections||[]).map(item=>`<tr>
<td><strong>${escapeHtml(item.associateName)}</strong></td><td>${escapeHtml(plate(item.plate,true))}</td><td>${item.requestType==='NEW_INSPECTION'?'Nova vistoria':'Atualização de boleto'}</td>
<td>${date(item.createdAt)}</td><td>${date(item.completedAt)}</td><td>${badge(item.status,INSPECTION_STATUS)}</td><td>${item.reportUrl?`<a class="button outline small-button" href="${escapeHtml(item.reportUrl)}" target="_blank" rel="noopener">Abrir</a>`:'—'}</td>
<td>${communicationCell(item)}</td>
</tr>`).join('')||empty(8,'Nenhuma vistoria encontrada para este consultor.');
document.querySelectorAll('[data-completion-message]').forEach(button=>button.addEventListener('click',()=>openCompletionCommunication(button.dataset.completionMessage)));}
function communicationCell(item){if(item.completionMessagePending&&item.associateCompletionWhatsappUrl)return `<button class="secondary small-button" data-completion-message="${escapeHtml(item.id)}" type="button">Enviar mensagem</button>`;if(item.completionMessageSentAt)return '<span class="badge ok">Informado</span>';if(item.completedAt&&!item.associateCompletionWhatsappUrl)return '<span class="badge off">Sem WhatsApp</span>';return '—'}
function startDashboardPolling(){stopDashboardPolling();dashboardTimer=window.setInterval(()=>loadDashboard(selectedConsultant,{silent:true}).catch(()=>{}),20000)}
function stopDashboardPolling(){if(dashboardTimer){window.clearInterval(dashboardTimer);dashboardTimer=null}}
function showNextCompletionCommunication(){if($('consultant-whatsapp-dialog').open)return;const next=(dashboardData?.inspections||[]).find(item=>item.completionMessagePending&&item.associateCompletionWhatsappUrl&&!dismissedCompletionIds.has(item.id));if(next)openCompletionCommunication(next.id)}
function openCompletionCommunication(id){const item=(dashboardData?.inspections||[]).find(value=>value.id===id);if(!item?.associateCompletionWhatsappUrl)return;activeCompletionCommunication=item;$('consultant-whatsapp-text').textContent=`A vistoria de ${item.associateName} foi concluída. Comunique ao associado que ela foi realizada e agora aguarda análise.`;$('consultant-whatsapp-details').innerHTML=`<div><span>Associado</span><strong>${escapeHtml(item.associateName)}</strong></div><div><span>Veículo</span><strong>${escapeHtml(plate(item.plate,true))}</strong></div><div><span>Concluída em</span><strong>${escapeHtml(date(item.completedAt))}</strong></div>`;$('consultant-whatsapp-dialog').showModal()}
async function sendCompletionCommunication(){const item=activeCompletionCommunication;if(!item)return;window.open(item.associateCompletionWhatsappUrl,'_blank','noopener,noreferrer');const button=$('consultant-whatsapp-send');button.disabled=true;button.textContent='Registrando...';try{const updated=await api(`/api/consultant-dashboard/inspections/${encodeURIComponent(item.id)}/completion-message-sent`,{method:'POST'});const index=dashboardData.inspections.findIndex(value=>value.id===updated.id);if(index>=0)dashboardData.inspections[index]=updated;$('consultant-whatsapp-dialog').close();activeCompletionCommunication=null;renderDashboard(dashboardData);message('Mensagem preparada no WhatsApp. Comunicação registrada.','success');showNextCompletionCommunication()}catch(error){message(error.message)}finally{button.disabled=false;button.textContent='Enviar mensagem ao associado'}}

$('login-form').addEventListener('submit',async e=>{e.preventDefault();const box=$('login-message');box.textContent='';try{const data=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});localStorage.setItem(TOKEN_KEY,data.token);localStorage.setItem(ROLE_KEY,data.role);if(data.role==='ADMIN'){location.href='/admin/'}else if(data.role==='ANALYST'){location.href='/analise/'}else{location.reload()}}catch(err){box.className='message error';box.textContent=err.message}});
$('select-consultant').addEventListener('click',()=>{const value=$('consultant-search').value.trim().toLowerCase();const found=consultants.find(c=>c.name.toLowerCase()===value);if(!found)return message('Selecione um nome da lista ou cadastre um novo consultor.');applyConsultant(found)});
$('show-create').addEventListener('click',()=>{$('create-box').hidden=false;$('new-consultant-name').value=$('consultant-search').value;$('new-consultant-name').focus()});$('cancel-create').addEventListener('click',()=>{$('create-box').hidden=true});
$('create-consultant').addEventListener('click',async()=>{clearMessage();try{const c=await api('/api/consultants',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('new-consultant-name').value.trim()})});await loadConsultants();$('create-box').hidden=true;$('consultant-search').value=c.name;applyConsultant(c);message('Novo consultor cadastrado e selecionado. Ele já aparecerá no painel administrativo.','success')}catch(e){message(e.message)}});
$('change-consultant').addEventListener('click',changeConsultant);$('refresh-dashboard').addEventListener('click',()=>{dismissedCompletionIds.clear();loadDashboard().catch(error=>message(error.message))});$('consultant-whatsapp-send').addEventListener('click',()=>sendCompletionCommunication());$('consultant-whatsapp-later').addEventListener('click',()=>{if(activeCompletionCommunication)dismissedCompletionIds.add(activeCompletionCommunication.id);$('consultant-whatsapp-dialog').close();activeCompletionCommunication=null;showNextCompletionCommunication()});$('logout').addEventListener('click',logout);const defaultSgaUrl='https://sga.hinova.com.br/sga/sgav4_novohorizonte/v5/login.php';const configuredSgaUrl=window.NH_CONFIG?.sgaUrl;$('sga-card').href=configuredSgaUrl&&configuredSgaUrl!=='#'?configuredSgaUrl:defaultSgaUrl;boot();
