const TOKEN_KEY='nhPortalToken',ROLE_KEY='nhPortalRole',CONSULTANT_KEY='nhSelectedConsultant';
const $=id=>document.getElementById(id);let token=localStorage.getItem(TOKEN_KEY);let inspections=[];let activeDecisionCommunication=null;
const STATUS={CREATED:['Pendente','warn'],UNDER_REVIEW:['Em análise','warn'],COMPLETED:['Aguardando análise','warn'],APPROVED:['Aprovada','ok'],REJECTED:['Recusada','off'],CANCELLED:['Cancelada','off'],EXPIRED:['Expirada','off']};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const date=value=>value?new Date(value).toLocaleString('pt-BR'):'—';
function badge(status){const [label,kind]=STATUS[status]||[status,''];return `<span class="badge ${kind}">${esc(label)}</span>`}
function formatPhone(value){const d=String(value||'').replace(/\D/g,'');if(!d)return '';const local=d.startsWith('55')?d.slice(2):d;return local.length===11?`(${local.slice(0,2)}) ${local.slice(2,7)}-${local.slice(7)}`:d}
function clearSession(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(ROLE_KEY);localStorage.removeItem(CONSULTANT_KEY);token=null}
function showLogin(text=''){clearSession();$('analysis-login').hidden=false;$('analysis-view').hidden=true;$('logout').hidden=true;const box=$('login-message');box.className=text?'message error':'';box.textContent=text}
function showView(){$('analysis-login').hidden=true;$('analysis-view').hidden=false;$('logout').hidden=false}
function message(text,type='error'){const el=$('message');el.className=`message ${type}`;el.textContent=text;window.scrollTo({top:0,behavior:'smooth'})}
async function api(path,options={}){const headers=new Headers(options.headers||{});if(token)headers.set('Authorization',`Bearer ${token}`);const response=await fetch(window.NH_API?.backend(path)||path,{...options,headers});if(response.status===401||response.status===403){showLogin('Sua sessão expirou ou não possui acesso à equipe de análise.');throw new Error('Sessão inválida.')}if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.message||'Não foi possível concluir a operação.')}return response.status===204?null:response.json()}
async function boot(){if(!token)return;try{const me=await api('/api/auth/me');localStorage.setItem(ROLE_KEY,me.role);if(me.role==='ADMIN'){location.replace('/admin/');return}if(me.role!=='ANALYST'){location.replace('/colaborador/');return}showView();await load()}catch(error){if(!$('analysis-view').hidden)message(error.message)}}
async function load(){const button=$('refresh');button.disabled=true;try{inspections=await api('/api/analysis/inspections');render()}finally{button.disabled=false}}
function render(){const filter=$('filter').value.trim().toLowerCase();const rows=inspections.filter(item=>`${item.associateName} ${item.plate||''} ${item.consultantName} ${item.status}`.toLowerCase().includes(filter)).map(item=>`<tr>
<td><strong>${esc(item.associateName)}</strong><small class="table-code">${esc(formatPhone(item.whatsapp)||'Sem WhatsApp')}</small></td><td>${esc(item.plate||'0 km — sem placa')}</td><td>${esc(item.consultantName)}</td><td>${item.requestType==='NEW_INSPECTION'?'Nova vistoria':'Atualização de boleto'}</td><td>${date(item.completedAt||item.createdAt)}</td><td>${badge(item.status)}</td><td><button class="secondary small-button" data-analyze="${item.id}" type="button">Analisar</button></td>
</tr>`).join('');$('inspections-body').innerHTML=rows||'<tr><td colspan="7" class="empty-state">Nenhuma vistoria encontrada.</td></tr>';document.querySelectorAll('[data-analyze]').forEach(button=>button.addEventListener('click',()=>openInspection(button.dataset.analyze)))}
function details(items){return items.map(([label,value])=>`<div><span>${esc(label)}</span><strong>${esc(value??'—')}</strong></div>`).join('')}
function links(items){return items.filter(([url])=>url).map(([url,label])=>`<a class="button outline" href="${esc(url)}" target="_blank" rel="noopener">${esc(label)}</a>`).join('')}
function openInspection(id){const item=inspections.find(value=>value.id===id);if(!item)return;$('inspection-id').value=item.id;$('dialog-title').textContent=`${item.plate||'0 km — sem placa'} — ${item.associateName}`;$('inspection-status').value=['CREATED','EXPIRED'].includes(item.status)?'UNDER_REVIEW':item.status;$('inspection-note').value=item.adminNote||'';$('inspection-details').innerHTML=details([
['Associado',item.associateName],['CPF',item.maskedCpf],['WhatsApp',formatPhone(item.whatsapp)||'—'],['Consultor',item.consultantName],['Placa',item.plate||'0 km — sem placa'],['Tipo',item.requestType==='NEW_INSPECTION'?'Nova vistoria':'Atualização de boleto'],['Criada em',date(item.createdAt)],['Concluída em',date(item.completedAt)],['Arquivos enviados',item.assetCount],['Endereço',item.residenceAddress||'—']]);
const publicUrl=item.publicUrl?(window.NH_URLS?.retratoUrl(item.publicUrl)||item.publicUrl):null;$('inspection-links').innerHTML=links([[item.driveFolderUrl,'Abrir pasta no Drive'],[item.reportUrl,'Abrir relatório'],[item.signatureUrl,'Abrir assinatura'],[publicUrl,'Abrir link da vistoria']]);showNotificationButton(item);$('inspection-dialog').showModal()}
function showNotificationButton(item){const box=$('associate-notification');const button=$('notify-associate');if(item?.associateDecisionWhatsappUrl&&item.associateDecisionMessagePending){button.textContent=item.status==='APPROVED'?'Enviar aprovação ao associado':'Enviar recusa ao associado';button.dataset.inspectionId=item.id;box.hidden=false}else{button.removeAttribute('data-inspection-id');box.hidden=true}}
$('inspection-form').addEventListener('submit',async event=>{event.preventDefault();const id=$('inspection-id').value;try{const updated=await api(`/api/analysis/inspections/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:$('inspection-status').value,adminNote:$('inspection-note').value.trim()})});const index=inspections.findIndex(item=>item.id===updated.id);if(index>=0)inspections[index]=updated;render();showNotificationButton(updated);message('Análise salva com sucesso.','success');if(updated.associateDecisionWhatsappUrl&&updated.associateDecisionMessagePending){$('inspection-dialog').close();openDecisionCommunication(updated)}}catch(error){message(error.message)}});

function openDecisionCommunication(item){if(!item?.associateDecisionWhatsappUrl)return;activeDecisionCommunication=item;const approved=item.status==='APPROVED';$('decision-whatsapp-icon').textContent=approved?'✓':'!';$('decision-whatsapp-icon').classList.toggle('rejected',!approved);$('decision-whatsapp-text').textContent=approved?`A vistoria de ${item.associateName} foi aprovada. Comunique a aprovação ao associado.`:`A vistoria de ${item.associateName} foi recusada. Comunique a recusa e as orientações ao associado.`;$('decision-whatsapp-details').innerHTML=`<div><span>Associado</span><strong>${esc(item.associateName)}</strong></div><div><span>Veículo</span><strong>${esc(item.plate||'0 km — sem placa')}</strong></div><div><span>Novo status</span><strong>${approved?'Aprovada':'Recusada'}</strong></div>`;$('decision-whatsapp-dialog').showModal()}
async function sendDecisionCommunication(){const item=activeDecisionCommunication;if(!item)return;window.open(item.associateDecisionWhatsappUrl,'_blank','noopener,noreferrer');const button=$('decision-whatsapp-send');button.disabled=true;button.textContent='Registrando...';try{const updated=await api(`/api/analysis/inspections/${encodeURIComponent(item.id)}/decision-message-sent`,{method:'POST'});const index=inspections.findIndex(value=>value.id===updated.id);if(index>=0)inspections[index]=updated;$('decision-whatsapp-dialog').close();activeDecisionCommunication=null;render();message('Mensagem preparada no WhatsApp. Comunicação registrada.','success')}catch(error){message(error.message)}finally{button.disabled=false;button.textContent='Enviar mensagem ao associado'}}
$('notify-associate').addEventListener('click',()=>{const id=$('notify-associate').dataset.inspectionId;const item=inspections.find(value=>value.id===id);if(item)openDecisionCommunication(item)});
$('decision-whatsapp-send').addEventListener('click',()=>sendDecisionCommunication());
$('decision-whatsapp-later').addEventListener('click',()=>{$('decision-whatsapp-dialog').close();activeDecisionCommunication=null});

$('login-form').addEventListener('submit',async event=>{event.preventDefault();const box=$('login-message');box.textContent='';try{const data=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});localStorage.setItem(TOKEN_KEY,data.token);localStorage.setItem(ROLE_KEY,data.role);token=data.token;if(data.role==='ADMIN'){location.href='/admin/'}else if(data.role==='ANALYST'){showView();await load()}else{location.href='/colaborador/'}}catch(error){box.className='message error';box.textContent=error.message}});
$('filter').addEventListener('input',render);$('refresh').addEventListener('click',()=>load().catch(error=>message(error.message)));$('close-dialog').addEventListener('click',()=>$('inspection-dialog').close());$('cancel-dialog').addEventListener('click',()=>$('inspection-dialog').close());$('logout').addEventListener('click',()=>showLogin());boot();
